### ISSUE TITLE
Support environment variables for git token

### ISSUE THREAD

**Issue by orhun** [MarcoIeni/release-plz#1008]
## Motivations

e.g. I would like to use `GITHUB_TOKEN` variable instead of passing the token via `--git-token`. 

- Would you like to implement this feature? [y/n]

y

## Solution

Use `env` directive of clap to support environment variables for certain arguments.

## Alternatives

None.

## Additional context

Thanks for creating `release-plz`!

**Comment by MarcoIeni** [comment]
Makes sense. Should we call it `GIT_TOKEN` instead of `GITHUB_TOKEN`?
My reasoning is that release-plz also supports gitea.

**Comment by orhun** [comment]
In #1026, I added `env` directive only to the git token. Let me know if you think we can also add it to the other arguments. With a glance look, I think this should be enough/feasible though.

**Comment by MarcoIeni** [comment]
Yes, the PR looks good, thanks ❤️
