### ISSUE TITLE
Add a timeout when checking if a crate has been published

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1015]
@orhun had the issue where [this](https://github.com/MarcoIeni/release-plz/blob/a92629ed10b8bb42dde426c0f0001aebbb6fa70e/crates/release_plz_core/src/cargo.rs#L62) function never finished. We should add a timeout (1 minute?) so that at least we can report what the error is.

**Comment by orhun** [comment]
It gets stuck at this line:

https://github.com/MarcoIeni/release-plz/blob/a92629ed10b8bb42dde426c0f0001aebbb6fa70e/crates/release_plz_core/src/cargo.rs#L76

**Comment by MarcoIeni** [comment]
I see. Probably we can debug and check inside that function.
Btw, I was expecting release-plz to use the sparse protocol, since it's the default for crates.io :/

**Comment by orhun** [comment]
So I ran `strace` and there are a bunch of `(Connection timed out)` errors after doing some operations in `.cargo/registry/index` (there are logs such as `Compressing objects: 100%`). Is there a proper way to get debug output from `crates_index` library?

**Comment by MarcoIeni** [comment]
>  Is there a proper way to get debug output from crates_index library?

I had a look at the [codebase](https://github.com/frewsxcv/rust-crates-index). It seems they don't emit any logs. 😢 
I looked for strings such as `logs`, `tracing`, `info!`, `error!` but I didn't find anything.
