### ISSUE TITLE
[question] is there a way to query current branch of release-pr

### ISSUE THREAD

**Issue by dj8yfo** [MarcoIeni/release-plz#1018]
There's a need to trigger a custom configurable github actions step
to run right after releaze-plz workflow, which should commit to the release-plz pr branch, which the pr is usually called `chore: release`.
Is there a way to output the branch, that release-plz just created and use it as parameter for another step?

**Comment by dj8yfo** [comment]
Referencing [near-sdk-rs issue](https://github.com/near/near-sdk-rs/pull/1092) to provide the context where the question arose from.

**Comment by MarcoIeni** [comment]
Hi! 👋 

> is there a way to query current branch of release-pr

Yes, you can query the GitHub api. I do the same thing here:
https://github.com/MarcoIeni/release-plz/blob/a92629ed10b8bb42dde426c0f0001aebbb6fa70e/crates/release_plz_core/src/git/backend.rs#L238

> Is there a way to output the branch, that release-plz just created and use it as parameter for another step?

No. PR welcome!
