### ISSUE TITLE
config option to create draft release PRs

### ISSUE THREAD

**Issue by robjtede** [MarcoIeni/release-plz#1060]
## Motivations

- I'd like a one-click approach to running CI on release PRs when no additional commits are needed.
- Release PRs can rightly be considered as drafts until the maintainer is ready to release them.
- The manual action of un-drafing a PR can help with the problem where CI doesn't run on release PRs.

Would you like to implement this feature? yes

## Solution

A new config option similar to `git_release_draft`, maybe `pr_draft` where a value of `true` creates a draft PR.

## Alternatives

An `output` for release-plz-action allowing access to the URL of the release PR so that a later step can mark it as draft.

## Additional context

I want to reduce the number of manual steps needed as much as possible, I was very happy to see the `git_release_draft` option available to enable a one-click CD workflow without needing to add PATs to secrets.

**Comment by MarcoIeni** [comment]
Thanks for all your incredible contributions Rob <3
