### ISSUE TITLE
Automatically tag merged PRs with the version they've been released into

### ISSUE THREAD

**Issue by LukeMathWalker** [MarcoIeni/release-plz#1084]
## Motivations

It often happens, when looking for a feature or a bug fix, to land on a merged PR. The next question: was this released? In what version?

## Solution

Instead of having to mess around with the commit history, looking for the first release commit after the merge, it'd ideal to have a label, right on the merged PR, stating which version the PR was released into.

## Alternatives

It could be a comment instead of a label, but I do believe labels are the optimal solution: low notification noise for the maintainer, very easy to search via GitHub's PR search UI.

## Additional context

I was going through this ordeal this very morning and I thought of release-plz ❤️

**Comment by joshtriplett** [comment]
I would love to see this as well. Rather than a label, the "milestone" field seems perfect for this.

**Comment by MarcoIeni** [comment]
I can see people both wanting labels and milestones, so this could be configurable 👍

**Comment by MarcoIeni** [comment]
When https://github.com/MarcoIeni/release-plz/pull/1449 is released, you can use `gh pr edit <PR_NUMBER> --add-label <LABEL_NAME>` in CI to add the label you want to all PRs that belong to the release.
Same for milestones: `gh pr edit <PR_NUMBER> --milestone <MILESTONE_NUMBER>`
I will document this and close this issue 👍
Hopefully, the github action output will enable people to do more things with release-plz without the need to add new configuration options 👍

**Comment by MarcoIeni** [comment]
Documented how you can add labels and milestones to released prs [here](https://release-plz.ieni.dev/docs/github/output#example-add-labels-to-released-prs). Go crazy 🥳
