### ISSUE TITLE
Commits with breaking change footers are not reflected in the generated changelog

### ISSUE THREAD

**Issue by TobTheRock** [MarcoIeni/release-plz#1103]
## Bug description

Slightly related to https://github.com/MarcoIeni/release-plz/issues/687, as conventional commits may contain a breaking change footer.
We have a  [git-cliff.toml](https://github.com/goto-opensource/secure-frame-rs/blob/main/git-cliff.toml) which specifically displays breaking changes in the [change log](https://github.com/goto-opensource/secure-frame-rs/blob/main/CHANGELOG.md).

 When running `git-cliff` directly the changelog is generated as desired, but not when using   `release-plz update`

- Would you like to work on a fix? [y/n]
-y
I tracked down the core issue, the problem is that commits are filtered [here](https://github.com/MarcoIeni/release-plz/blob/main/crates/release_plz_core/src/next_ver.rs#L681) before they are passed to `git-cliff-core` . As a result the footers are not evaluated.  Removing the filter already fixes the issue. Was there any particular reason to filter the commits here?

## To Reproduce

1. Have a commit containing a breaking change footer, e.g.
```
feat: new awesome stuff

BREAKING CHANGE: breaks everything
```
2. have a `git-cliff` config, which has special handling for breaking changes, e.g.
```
...
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
          {% if commit.breaking %} \n {{ commit.breaking_description }}{% endif %}\
    {% endfor %}
...
{% endfor %}\n
``` 
3. Run `release-plz update`
## Expected behavior
Breaking change marked in the change log, e.g.

> ## [0.3.0] - 2023-10-28
> ### Features
>     - [breaking] new awesome stuff
>       breaks everything
> ...

## Environment

- OS: Arch Linux
- release-plz version: master

**Comment by TobTheRock** [comment]
I guess they take the whole commit, as when I run the `git-cliff` cli tool I got a different output. 
What I got from the `git-cliff` code it is intended to [have the "message including title, description and summary"](https://github.com/orhun/git-cliff/blob/main/git-cliff-core/src/commit.rs#L105)
Appears that the message is internally splitted into a conv commit [here](https://github.com/orhun/git-cliff/blob/main/git-cliff-core/src/commit.rs#L380) then.
I also played around with `release-plz`, commenting out the filtering. Works both with my git-cliff config and the default from `release-plz` as inteded (only the commit title appears in the change log).

**Comment by MarcoIeni** [comment]
Great, than we can remove that filter. Do you want to raise a PR? Than I will test it :)

**Comment by TobTheRock** [comment]
Sure, here it is: https://github.com/MarcoIeni/release-plz/pull/1104
Thanks :+1:

**Comment by MarcoIeni** [comment]
fixed by https://github.com/MarcoIeni/release-plz/pull/1104
Thanks 🙏
