### ISSUE TITLE
Commits with "feat:" increment patchlevel version number

### ISSUE THREAD

**Issue by intgr** [MarcoIeni/release-plz#1131]
## Bug description

I set up `release-plz` for my project [rocket-sentry](https://github.com/intgr/rocket-sentry) ([release-plz.toml file](https://github.com/intgr/rocket-sentry/blob/master/release-plz.toml)). The GitHub Actions workflow is almost verbatim from [Example: release-pr and release](https://release-plz.ieni.dev/docs/github/quickstart#example-release-pr-and-release) from docs.

I've tried to use `feat:` to signal a minor release bump, but `release-plz` is only bumping patch version.

First: https://github.com/intgr/rocket-sentry/commit/b62415dbe7e4bf395f49a8c32d88242a8970ca68 commit starts with `feat(deps):`, but if you look at the initial version of this PR description (before my manual changes) https://github.com/intgr/rocket-sentry/pull/68, `release-plz` wanted to update 0.16.0 -> 0.16.1

Second: https://github.com/intgr/rocket-sentry/commit/18e8c50c56969e267d3acd784dfc06343d6c3507 commit with `feat:` and the PR created https://github.com/intgr/rocket-sentry/pull/70 only bumps 0.17.0 -> 0.17.1

Logs from second run: https://github.com/intgr/rocket-sentry/actions/runs/7161770256/job/19497836806

Have I misconfigured something?

- Would you like to work on a fix? [y/n] possibly, but I need help with troubleshooting

## To Reproduce

Not sure exactly, maybe try running `release-plz` on my repository locally.

## Expected behavior

The presence of a `feat` commit should result in a minor (not patch) version bump.

## Environment

- OS: Ubuntu 22.04.3 (GitHub Actions CI)
- release-plz version: 0.3.32

## Additional context

Another weird quirk is that running `git cliff` locally, git commit authors get added to changelog. But release-plz somehow does not preserve commit authors.

E.g. commit https://github.com/intgr/rocket-sentry/commit/aa4df5a2e338bfe1e0b52dfb1c949a8039418cc5 should have resulted in a line "Contributed by Hugo-C", but it was omitted in the changelog generated by `release-plz` in https://github.com/intgr/rocket-sentry/pull/64. [Relevant part of cliff.toml](https://github.com/intgr/rocket-sentry/blob/7d8614e5d950e01ba182abe86252f9d4e5ba55fd/cliff.toml#L50-L52)

**Comment by MarcoIeni** [comment]
Hi, thanks for the detailed bug report. This is the intended behavior.
I opened https://github.com/MarcoIeni/release-plz/pull/1132 to document my reasoning better.
E.g. `axum` recently went from 0.6.x to 0.7.0 because they had breaking changes. Otherwise they would have continued with 0.6.x.

> release-plz somehow does not preserve commit authors.

This is because release-plz uses its own default configuration:
https://github.com/MarcoIeni/release-plz/blob/02d13a1b537faf9fb305d8e711b8ef96ce46bcf3/crates/release_plz_core/src/changelog.rs#L225

Feel free to contribute to make it better :)

**Comment by MarcoIeni** [comment]
I know! Having https://github.com/MarcoIeni/release-plz/issues/704 would be awesome, but I'm not there yet. Help is appreciated of course :)

**Comment by MarcoIeni** [comment]
In the meantime you can use the `set-version` command from https://github.com/killercup/cargo-edit
but it doesn't update the changelog
