### ISSUE TITLE
Release-plz reads the config, but the release PR does not contain the changelog as it is configured

### ISSUE THREAD

**Issue by sassman** [MarcoIeni/release-plz#1133]
## Bug description

At cargo-generate I'm trying out release-plz, and have configured the git-cliff to look a bit different than usual. [As from the CI Run](https://github.com/cargo-generate/cargo-generate/actions/runs/7180158462/job/19551826017#step:4:139) you can see that release-plz does read the config file AND the right git-cliff config file. (You'll notice the emojis in the convential commit categories)

So far so good, however the [release-pr that is created does not contain the CHANGELOG changes](https://github.com/cargo-generate/cargo-generate/pull/1080/files).

I was able once to get a CHANGELOG change in the PR, but this one did not correctly utilize the configuration provided by the [git-cliff config](https://github.com/cargo-generate/cargo-generate/blob/main/cliff.toml) in the repo. 

- Would you like to work on a fix? yes, but I have no idea where to look at.

## To Reproduce

1. create a [release-plz config like this](https://github.com/cargo-generate/cargo-generate/blob/main/release-plz.toml)
2. create a [git-cliff config like this](https://github.com/cargo-generate/cargo-generate/blob/main/cliff.toml) (as above)
3. create a [simple GH Pipeline like this](https://github.com/cargo-generate/cargo-generate/blob/main/.github/workflows/release-pr.yml)
4. see that the PR does not contain a CHANGELOG

## Expected behavior

I would expect the CHANGELOG.md is updated and the change is in the release-pr.

## Environment

- OS: ubuntu-latest on GithubActions
- release-plz version: release-plz-v0.3.33/linux-x64

**Comment by MarcoIeni** [comment]
Removing `previous.version` from the changelog works. We should populate this field and pass it  to git-cliff somehow.

**Comment by MarcoIeni** [comment]
It's also bad that we are panicking:
```
thread 'main' panicked at crates/release_plz_core/src/changelog.rs:69:14:
cannot update changelog: TemplateRenderError("Variable `previous.version` not found in context while rendering 'template'")
```

**Comment by MarcoIeni** [comment]
Also, you can use `release-plz update` to test locally if you don't want to push commits

**Comment by MarcoIeni** [comment]
We can set previous here:
https://github.com/MarcoIeni/release-plz/blob/986bbc4c187258eb644f6b6361e3d25168975550/crates/release_plz_core/src/changelog.rs#L152

**Comment by sassman** [comment]
Thanks a lot for the swift reply and taking action.

**Comment by MarcoIeni** [comment]
Hey Sven, I just released a new version of release-plz.
I tested release-plz on it. The only issue I found is that the git tag link unfortunately doesn't work:

```
## [0.18.6] 2023-12-13

[0.18.6]: <REPO>/compare/0.18.5...0.18.6
```

For the default changelog, I set it manually:

https://github.com/MarcoIeni/release-plz/blob/6c1feea3f53caf4ba9247c7fc9f0cf364b426c14/crates/release_plz_core/src/changelog.rs#L115

Unfortunately, release-plz doesn't support git-cliff to 100% yet.

**Comment by sassman** [comment]
Thank you so much Marco, 

looks already pretty good. I changed the body template a bit so that It accommodates for the missing link.

![image](https://github.com/MarcoIeni/release-plz/assets/329682/6d4e055c-15e2-437d-b8a5-9e292d8152f0)

https://github.com/cargo-generate/cargo-generate/pull/1080/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3

There is only and interesting (unrelated) issue with the diff of the CHANGELOG.md where the top header `# Changelog` is being appended in the diff at the bottom. 

That is strange, but I will have a look and see if I can find the bug myself.

**Comment by sassman** [comment]
and BTW: 

> Also, you can use release-plz update to test locally if you don't want to push commits

This works, but it does not produce the same release version as it does on CI. Specifically it does not detect the breaking change and bumps the maj. version number, only the patch version number. Not sure if that is intended.

**Comment by MarcoIeni** [comment]
For that, you need to install cargo-semver-checks locally
