### ISSUE TITLE
Version not being updated

### ISSUE THREAD

**Issue by jdidion** [MarcoIeni/release-plz#1139]
I did the following in this repository: https://github.com/jdidion/jd-test-repo

* Push an initial commit to `main` that included all code, including the release workflow, and an initial version of `0.1.0`
* release-plz created a release PR
* I merged the release PR and release-plz correctly created the release for version `0.1.0`
* I created a new branch
* I pushed changes to the new branch
* I created a PR from the new branch
* I squash merged the PR into `main` with a commit message prefixed with `fix:`

Expected behavior: release-plz detects the change and creates a new release PR with version `0.1.1`

Actual behavior: release-plz did not create a new release PR

**Comment by MarcoIeni** [comment]
Did you created the v0.1.0 tag manually?
Release-plz is not releasing your crate to crates.io because the tag already exist.
Also, release-plz doesn't update the version because the crate has not been published.

**Comment by MarcoIeni** [comment]
To fix, I suggest to run `cargo publish` manually for this time

**Comment by jdidion** [comment]
I did not create the tag manually. It was created by release-plz.

That makes sense that the version is not updated because the crate has not been published. Would you consider a feature request to update the version based on changes since the last release tag regardless of whether it has been published? This would at least be useful for testing. I would be willing to make a PR for this.

**Comment by MarcoIeni** [comment]
> I did not create the tag manually. It was created by release-plz.

Oh, I see. Release-plz didn't publish on crates.io because you have `publish = false` in release-plz.toml.

>  Would you consider a feature request to update the version based on changes since the last release tag regardless of whether it has been published?

I considered this in https://github.com/MarcoIeni/release-plz/issues/590, but I ended up discarding the idea. Let me know what you think :)

**Comment by jdidion** [comment]
Thanks, I missed that issue. I like the idea of `git_only` but I also understand this being a use case you do to support. If you change your mind feel free to reopen the issue and assign it to me.

**Comment by MarcoIeni** [comment]
I created https://github.com/MarcoIeni/release-plz/issues/1144 but I can't assign the issue to you. Maybe leave a comment there :)

In the meantime, I created https://github.com/MarcoIeni/release-plz/pull/1143 to explain what's happening in the code.

**Comment by jdidion** [comment]
Great, thanks! I will try to find time to work on this soon.
