### ISSUE TITLE
Error on cargo lock

### ISSUE THREAD

**Issue by 0xJepsen** [MarcoIeni/release-plz#1151]
## Bug description

When the CI action runs, i keep getting this error about the `cargo.lock` that reads 
```
note: Downloading arbiter 0.4.13
 Downloading crates ...
  Downloaded arbiter v0.4.13
  2023-12-19T16:09:03.424747Z ERROR  error while running git with args `["checkout", "main"]:
- stderr: error: Your local changes to the following files would be overwritten by checkout:
	Cargo.lock
Please commit your changes or stash them before you switch branches.
Aborting

Error: error while running git with args `["checkout", "main"]:
- stderr: error: Your local changes to the following files would be overwritten by checkout:
	Cargo.lock
Please commit your changes or stash them before you switch branches.
Aborting
Error: Process completed with exit code 1.
```

the yml i have looks like
```yml
name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Commit Cargo.lock
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.lock
          git commit -m "Update Cargo.lock" || (git add Cargo.lock && git commit -m "Update Cargo.lock") || echo "No changes to commit"
      - name: Check git status
        run: git status
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
```

- Would you like to work on a fix? [y]

## To Reproduce

The bug exists in the main branch of our repository [here](https://github.com/primitivefinance/arbiter/actions/runs/7264448902/job/19792007084)

## Expected behavior

Expected behavior is that the release-plz action succeeds and opens the release PR

I feel like i could be missing something simple but i am not sure where i am going wrong. The tool usually functions as intended and has been really useful for us. I have tried recommitting the `cargo.lock` but things are still failing.

**Comment by MarcoIeni** [comment]
I can reproduce this by running `release-plz update` locally in the repository, nice 👍 
I'm looking

**Comment by MarcoIeni** [comment]
Here's the fix: https://github.com/MarcoIeni/release-plz/pull/1152

You can compile release-plz locally on this branch and run it locally on your repo.
I will ship this fix soon in the GH action.

**Comment by hseeberger** [comment]
Thanks @0xJepsen for reporting.
Thank you @MarcoIeni, for the quick fix!

**Comment by 0xJepsen** [comment]
Thanks for the prompt fix!

**Comment by MarcoIeni** [comment]
I released the new version of the GitHub action, let me know if you still have problems :)

**Comment by 0xJepsen** [comment]
> You can compile release-plz locally on this branch and run it locally on your repo.
> I will ship this fix soon in the GH action.

What is the best way to update the github action? Do i need to do this? Unsure how to test the fix

**Comment by 0xJepsen** [comment]
still getting the error here
```
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `artemis-core` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
  2023-12-21T21:59:44.129772Z ERROR  failed to release package

Caused by:
    failed to publish arbiter-engine:     Updating crates.io index
    error: all dependencies must have a version specified when publishing.
    dependency `artemis-core` does not specify a version
    Note: The published dependency will use the version from crates.io,
    the `git` specification will be removed from the dependency declaration.

Error: failed to release package

Caused by:
    failed to publish arbiter-engine:     Updating crates.io index
    error: all dependencies must have a version specified when publishing.
    dependency `artemis-core` does not specify a version
    Note: The published dependency will use the version from crates.io,
    the `git` specification will be removed from the dependency declaration.
Error: Process completed with exit code 1.
```

**Comment by 0xJepsen** [comment]
Is is possible that it's because one of the crates hasn't been updated yet?

**Comment by MarcoIeni** [comment]
> What is the best way to update the github action? 

If you use `MarcoIeni/release-plz-action@v0.5` [here](https://github.com/primitivefinance/arbiter/blob/3bcb5deebc6896652612fab7a6e1e67346cf3181/.github/workflows/release-plz.yml#L30C15-L30C48), you will get the latest v0.5.x version.
E.g. when I publish v0.5.34 you won't need to change anything, while if you are on `MarcoIeni/release-plz-action@v0.5.33` you would need to update manually.

Anyway, now you are on v0.5.33 which is the [latest](https://github.com/MarcoIeni/release-plz-action/releases) 👍 

Now I'm checking your error 👀

**Comment by MarcoIeni** [comment]
Your error doesn't depend on release-plz.

```
cd arbiter-engine
cargo publish --dry-run
```

**Comment by MarcoIeni** [comment]
[Here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) the cargo book explain the reason:
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/15beb471-4732-4688-b302-95671cbb461d)

**Comment by 0xJepsen** [comment]
Thank you
