### ISSUE TITLE
Configuration: add ability to customize github release body

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1202]
## Motivations

Now release-plz populates the github release body with the changelog. 
People might want different things.

## Solution

We could have a configuration field called `git_release_body`. It is a tera template where people can customize how their releases look. Similar to `git_tag_name`.
A variable called `{{ changelog }}` should be populated with the changelog entry of the release.
The default configuration is `git_release_body = "{{ changelog }}"`, which is the current behavior.

An example configuration might be

```toml
git_release_body = """Hey, welcome to the new release, here's what changed:
{{ changelog }}
"""
```

**Comment by giangndm** [comment]
@MarcoIeni Can we split the changelog into smaller sections such as features, bugs, chores, or contributors? It would be more flexible that way.

**Comment by MarcoIeni** [comment]
Maybe we should provide the same level of customizability we provide for the changelog `body` field. For now, let's just provide the changelog variable, because I feel like it could be useful anyway.
Then we can reason about more customizability. What do you think?

**Comment by MarcoIeni** [comment]
Closed by https://github.com/MarcoIeni/release-plz/commit/2733209ba1967db3b2688c88079b17e2fe35e0c6
