### ISSUE TITLE
Only one single-package release PR can be open at once

### ISSUE THREAD

**Issue by jbr** [MarcoIeni/release-plz#1216]
## Bug description

I'm trying to use release-plz without automatic PR generation, and instead running `release-plz release-pr -p some-workspace-crate`. I expected to be able to open multiple PRs like that by running it several times in sequence, but the second one closed the first. I then tried running `release-plz release-pr -p workspace-crate-one -p workspace-crate-two` and `release-plz release-pr -p workspace-crate-one,workspace-crate-two`, since a single PR with the multiple releases would work fine for my use case. Neither of those worked.

Example PR that was renamed: https://github.com/trillium-rs/trillium/pull/525#event-11541825465

Is this an intended use case? I can serialize the releases to work around this but it saves time to run CI on the release PRs in parallel

- Would you like to work on a fix? [y/n] y

**Comment by MarcoIeni** [comment]
> but the second one closed the first

yes, that's the intended behavior unfortunately.

We need https://github.com/MarcoIeni/release-plz/issues/1029 to support this behavior.
