### ISSUE TITLE
release-pr doesn't update dependencies

### ISSUE THREAD

**Issue by dousto** [MarcoIeni/release-plz#1218]
## Bug description

I noticed a difference in output between `update` and `release-pr` commands. `update` was correctly updating dependencies that had version bumps, however `release-pr` was not.

I created #1217 which is a quick path to resolution. However, if you want to use a different approach more suitable to recent refactoring I will not be offended 😄 .

- Would you like to work on a fix? see PR

## To Reproduce

1. Use a workspace that has at least two crates (A, B), where A depends on B.
2. Commit something to B.
3. Run `release-plz update` and compare the changes to `release-plz release-pr`.

## Expected behavior

I expected the changes produced from `release-plz update` and `release-plz release-pr` to be identical.

## Environment

- OS: _
- release-plz version: 0.3.39

**Comment by MarcoIeni** [comment]
closed by https://github.com/MarcoIeni/release-plz/pull/1217
