### ISSUE TITLE
Cannot compare diff with only GitHub released packages

### ISSUE THREAD

**Issue by ozgunozerk** [MarcoIeni/release-plz#1221]
## Bug description

I'm testing this action in a fork. And I've released the first version of the package (as a GitHub release, not released on crates.io). 

When I made some conventional commits, and triggered the workflow again, I got this error:

```
  2024-01-22T11:50:52.199660Z ERROR  failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference between packages
    2: package `oz-parachain-template-runtime` not found in the registry, but the git tag oz-parachain-template-runtime-v0.1.0 exists. Consider running `cargo publish` manually to publish this package.
```

So, although `publish=false` exist in `release-plz.toml` config file, I don't know why it tried to download my custom package from `crates.io` and compare the versions...

- Would you like to work on a fix? [y/n] y (I might require some guidance)

## Expected behavior

It already found a git tag (look at the error message above). I'd expect it to compare the package with the latest git tag (if `publish=false` is present in `release-plz.toml`.

## Environment

GitHub actions (default settings with Ubuntu)

## Additional context

I looked at the CLI tool, and found out there is `--registry-project-manifest` flag there. I think it is related to my problem, since the explanation for that flag is:
```
Path to the Cargo.toml contained in the released version of the project you want to update. If not provided, the packages of your project will be compared with the ones published in the cargo registry. Normally, this parameter is used only if the published version of your project is already available locally. For example, it could be the path to the project with a `git checkout` on its latest tag. The git history of this project should be behind the one of the project you want to update
```

but I couldn't find a way to set this in GitHub actions 🤷

**Comment by MarcoIeni** [comment]
Is this a duplicate of https://github.com/MarcoIeni/release-plz/issues/1144 ?

**Comment by ozgunozerk** [comment]
Yes! I'll carry the details of this one to there. Closing this one
