### ISSUE TITLE
Add ability to manually tag a PR as breaking

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#1252]
## Motivations
cargo-semver-checks isn't perfect and there's stuff that can it miss, leading a new release to be marked as patch when it is in fact breaking. It would be great if there was a way through a commit message, or a comment on the PR, if release-plz could know, that it is in fact a breaking change and mark the release as a new major version even though cargo-semver-checks passed.

- Would you like to implement this feature? n

**Comment by MarcoIeni** [comment]
Hi 👋 

When committing the breaking change, you can add a `!` in the title to explicitly mark the commit as breaking. More info [here](https://www.conventionalcommits.org/en/v1.0.0/).

E.g. `feat!: send an email to the customer when a product is shipped`.

However, there's no way to change this from the release PR.
It looks like this issue could be solved by #704

**Comment by MarcoIeni** [comment]
OT (it was the easiest way to reach to you 😄):

I added this section to the release-plz [homepage](https://release-plz.ieni.dev/) with some wonderful feedback I received. ❤️
If you don't want to be listed there, let me know and I will remove your quote 👍
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/7dab4473-30e7-49d9-bf67-2b11377ddd16)

**Comment by XAMPPRocky** [comment]
Looks great!

**Comment by MarcoIeni** [comment]
Ooops, sorry! 😅  Fixed in https://github.com/MarcoIeni/release-plz/pull/1264 👍

**Comment by MarcoIeni** [comment]
I'm closing this because I think it can be satisfied by https://github.com/MarcoIeni/release-plz/issues/704
I.e. if the next version is `1.2.3` but instead you want to signal a breaking change, in the future you'll be able to write `release-plz set-version 2.0.0` in the github pr as a comment. I think it should be good enough. But let me know if you have other ideas.
