### ISSUE TITLE
prepare release only if at least one commit respects a certain regex

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1274]
## Motivations

It might be too noisy to raise PRs on every commit.
E.g. some people might not want to release the crate if the commits contain only `chore`s.

## Solution

We should have a `release_commits` field in the [workspace](https://release-plz.ieni.dev/docs/config#the-workspace-section) section of the configuration.
In `release-plz update` and `release-plz release-pr` we should bump the version and update the changelog of the crate only if at least one of the [commits](https://github.com/MarcoIeni/release-plz/blob/160c433715c3e5b395e59dc538d0908f10ee097a/crates/release_plz_core/src/diff.rs#L9) matches that regex.

E.g., if I want to only release when there's a new feature I write `release_commits = "^feat:" in the config.

Please update the doc too.

## Additional context

Requested [here](https://github.com/MarcoIeni/release-plz/issues/1181#issuecomment-1875847628).

**Comment by MarcoIeni** [comment]
I think that should be a good place, yes.
But I haven't tested it so I might be wrong!

**Comment by isidzukuri** [comment]
Im not sure i will be able to finalize PR but i've tried to poke around. Feel free to use it if it makes sense https://github.com/MarcoIeni/release-plz/pull/1278. Currently i'm feeling lack of automated tests. And i haven't tested it manually, must study documentation to understand how to do it properly. 

However existing tests passed successfully except `generate_schema::tests::schema_is_up_to_date`. Some other  are failing when updating `.schema/latest.json`:
```
changelog::release_plz_adds_changelog_on_new_project
changelog::release_plz_adds_custom_changelog
changelog::release_plz_releases_a_new_project
helpers::gitea::gitea_new::can_create_gitea_repository
release::release_plz_releases_a_new_project_with_custom_release_name
release::release_plz_releases_a_new_project_with_custom_tag_name
```
Perhaps im doing smtn wrong. Didn't have enough time to figure it out.

Would be glad to know if i moved in right direction :detective:

**Comment by MarcoIeni** [comment]
To make schema_is_up_to_date test pass, just run `cargo run -- generate-schema` as explained in the comment of the test itself:
https://github.com/MarcoIeni/release-plz/blob/013ff9263e7e652be50331e6d74e834aee9e2ddc/crates/release_plz/src/generate_schema.rs#L43

I have done it for you 👍 

for the other tests, you need to run docker as explained [here](https://github.com/MarcoIeni/release-plz/blob/main/CONTRIBUTING.md#integration-tests). 👍

**Comment by MarcoIeni** [comment]
I looked at the PR, looks good. I need to test it.
If you want to write an integration test in the meantime, you can take inspiration from this:
https://github.com/isidzukuri/release-plz/blob/1810d9df33ec87e12dc48b3acf9c32ddad4b9e39/crates/release_plz/tests/all/changelog.rs#L5

**Comment by isidzukuri** [comment]
Thank you! :+1: 

I will try to write an integration test :speak_no_evil:

**Comment by isidzukuri** [comment]
@MarcoIeni i have an idea how to save time on responding to  inattentive contributors :smile: , please take a look https://github.com/MarcoIeni/release-plz/pull/1285

**Comment by MarcoIeni** [comment]
I added a small integration test myself because I wanted to merge this today. Thanks for your contribution ❤️
