### ISSUE TITLE
release-plz PRs getting 403

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#1279]
I haven't made any changes to the release plz setup in `rasn`, but recently it has now started to fail consistently.

```
  2024-02-18T18:58:08.362654Z ERROR  Failed to open PR

Caused by:
Error: Failed to open PR

Caused by:
    HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/librasn/rasn/pulls)
    HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/librasn/rasn/pulls)
```

https://github.com/librasn/rasn/actions/runs/7951055915/job/21704049615

**Comment by MarcoIeni** [comment]
Maybe the github token expired? 🤔

**Comment by XAMPPRocky** [comment]
> Maybe the github token expired?

I'm not sure how it would, because it's using the builtin `GITHUB_TOKEN`, and this is failing at the GitHub part, not the cargo part which is a token I added, but that also doesn't have an expiry.

**Comment by MarcoIeni** [comment]
I see. Can you check the docs to see if you are missing any permission?
https://release-plz.ieni.dev/docs/github/quickstart

Maybe github changed some default 🤔

**Comment by MarcoIeni** [comment]
Happy to see that release-plz is working again for you. 🥳
I'm closing this issue. Did you change something in the repo to make release-plz work?
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/20adbfea-5cd4-455a-b9e3-c55689d81dfb)

**Comment by XAMPPRocky** [comment]
Yes, there was a new permission added that was defaulted to off, which is "allow actions to create and update PRs".
