### ISSUE TITLE
The following overrides are not present in the workspace

### ISSUE THREAD

**Issue by baszalmstra** [MarcoIeni/release-plz#1288]
## Bug description

- Would you like to work on a fix? y

## To Reproduce

1. In [this repository](https://github.com/mamba-org/rattler) if I add the following releaze-plz.yml:

```toml
[workspace]

[[package]]
name = "rattler-bin"
release = false

[[package]]
name = "tools"
release = false
```

2. Run `release-plz.exe update` and observe the following error:

```shell
❯ release-plz.exe update
  2024-02-23T10:34:54.003264Z  INFO  using release-plz config file release-plz.toml

  2024-02-23T10:34:54.421852Z ERROR  failed to determine next versions

Caused by:
    The following overrides are not present in the workspace: `rattler-bin`, `tools`. Check for typos

Error: failed to determine next versions

Caused by:
    The following overrides are not present in the workspace: `rattler-bin`, `tools`. Check for typos
```

## Expected behavior

The repository contains a Cargo workspace which includes (among others) the packages `rattler-bin` and `tools`. I would expect release-plz 

## Environment

- OS: Windows 11
- release-plz version: release-plz 0.3.45

**Comment by baszalmstra** [comment]
I was eventually able to exclude the packages by adding

```toml
[package]
...
publish = false
```

to the packages I don't want.

**Comment by MarcoIeni** [comment]
I confirm there's a bug, I will try to fix it 👍 
But the workaround is valid, thanks 🙌
