### ISSUE TITLE
Don't immediately publish new crates to crates.io

### ISSUE THREAD

**Issue by Alxandr** [MarcoIeni/release-plz#1289]
## Motivations

Most of my projects consists of workspaces with more than 1 crate. When I add new crates to these, `release-plz` will immediately try to publish to crates.io (for those new crates) without going through the release PR.

- Would you like to implement this feature? [y/n]

## Solution

release-plz should wait to release the new crates til the release-pr is merged (changelog is generated etc.)

**Comment by MarcoIeni** [comment]
I understand how this can be frustrating, but release-plz can also work without release-pr. E.g. you can run `release-plz update`, and then commit and push.
Also, some people just use `release-plz release` without using other release-plz commands.
So I think this change is too big to happen, at least for now.

However, with some CI magic, we could obtain the intended behavior 🤔 

What if you only run `release-plz release` if the commit is the release-pr. E.g. you can check:
- the author of the commit ( you should be able to do it in [this](https://stackoverflow.com/a/73099767) way )
- the commit message (it respects the regex `chore(optional_context): release`
- other ideas?

What do you think? If it works for you, it would be nice to document this in the github action [docs](https://release-plz.ieni.dev/docs/github) somewhere.

**Comment by Alxandr** [comment]
I don't like checking the commit message (as that can be a bit brittle). The committer would probably work though. That being said, having to "work around" this is a bit unfortunate. It would be much better if this was simply a config value in release-plz. That makes adopting it to new repos much easier.

**Comment by MarcoIeni** [comment]
How would the config value work?

**Comment by Alxandr** [comment]
I'm assuming `release-plz` knows if it's running in a release commit? If not, that's the first part I would add support for. Then it would simply be something like `only_publish_in_release_commits` or somesuch.

**Comment by MarcoIeni** [comment]
Release-plz doesn't know if the last commit is a release commit. I think the only ways to know are to match the commit message or the commit author 🤔

**Comment by Alxandr** [comment]
I'm used to `release-please` where I'm able to take actions (like publishing crates) if and only if a new release was just created (ie, it's running on the release commit). I'm not entirely sure how it does this - though I think it can be done by checking the commit against merged PRs - and checking if the PR is a release PR.

**Comment by MarcoIeni** [comment]
How do you understand if a pr is a release pr? :P
Yeah, looking into how release-please does it is a good idea 👍

**Comment by Alxandr** [comment]
With PRs you have a lot more data to work with. You could specify a tag for instance - or the PR author (which is not necesarily the same as the merger). But yes, at the end of the day, you are sort of just pushing the problem back.

**Comment by MarcoIeni** [comment]
Yeah, in the end I think it's up to personal preference, and we can't have a simple `only_publish_in_release_commits = true` imo.

> You could specify a tag for instance

For example, labels in PRs can be enabled with the [pr_labels](https://release-plz.ieni.dev/docs/config#the-pr_labels-field) config field, but there are none by default.

So for now I think the best solution is to let user customize this behavior in CI.

**Comment by matthiasg** [comment]
Honestly I am confused by the default setup as described in the documentation. What is the purpose of opening up pull-requests when it then immediately pushes them and does not even wait for all tests to finish ?

**Comment by MarcoIeni** [comment]
> Honestly I am confused by the default setup as described in the documentation

I'll improve the docs 👍 If you have any suggestions, feel free to open a pr

> does not even wait for all tests to finish ?

which tests?

**Comment by matthiasg** [comment]
@MarcoIeni I am coming from @microsoft/rush (large node.js project) and use our own hosted gitlab instance. 

In our CI we run our builds (all projects), run the tests , extract the public facing apis (typescript compiler), check for any changes (but do not yet calculate major,minor based on that) and when all builds are completed and all tests are satisfied (including coverage where configured) rush will then publish the packages (the ones marked public to npm, the rest to our own repo). It will never publish before build and tests are done correctly.

release-plz looks very close to this, but the default setup in the docs did not mention testing (unit,integration, and docs) and it seems it publishes as long as it builds.

Based on your talk I thought i could configure it to look at a branch (eg. master), get triggered (github), calculate the changelog and new semvers, update the workspace versions   and create a pull-request which i could then merge (auto or manual). upon this merge it would then build once more (tests and all) and if everything works publish all crates.

It seems this is almost like it works, but I seem to be missing something. I will take some time later this afternoon and will look into it again, but any pointers here would be valuable to me.

**Comment by MarcoIeni** [comment]
First of all thank you for your donation 🙏 

> It will never publish before build and tests are done correctly.

Cool! Release-plz is a bit more modular. For example, in GitHub actions you can write something like this:

```yaml
jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo test # <-- put any check you like here 
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
```

I never to this because I run tests, lints, etc in every [pr](https://github.com/MarcoIeni/release-plz/blob/main/.github/workflows/ci.yml). So when I merge the PR I don't need for release-plz to run them again.

**Comment by matthiasg** [comment]
I meant it isn't part of https://release-plz.ieni.dev/docs/github/quickstart which i think is dangerous as a guide. Will look into the pr process you use. going from the defaults i did not get the flow i was hoping for yet.

PS: The donation is just a coffee or two for your time :)

**Comment by Alxandr** [comment]
I also feel the release-please workflow is much better. The process there is like this:

1. I push to (or merge to) main
2. Release-please runs and creates/updates a PR
3. Tests runs on this "release pr"
4. After tests pass, I check the PR and the generated changelog
5. I merge the PR
6. Release-please runs on the release-commit and publishes

**Comment by MarcoIeni** [comment]
You are missing:
- step 7: run cargo publish by yourself, which release-plz does
- step 8: manually check if semver was violated, which release-plz checks with cargo-semver-checks.

😛 

steps 1 to 5 are the same for release-plz.
for step 6 we just need this issue to be fixed. 💪

**Comment by Alxandr** [comment]
I don't run cargo publish by myself. It happens in the same github action that runs release-please. But sure, the semver violation checks are definitely one of the reasons I'm trying out release-plz for my projects. That and some rust-related issues I've had with release-please.

**Comment by MarcoIeni** [comment]
I just had an idea while I'm trying to get asleep on how to implement the only_publish_in_release_commits flag.
If this is true we could force the user to specify the pr_labels field in the config.
Or maybe if empty we default to a default label. E. G. Type:pr
Then we use github api to check if the commit belongs to a pr with this label. - Alxandr suggested a similar flow a few issues above!
