### ISSUE TITLE
Add ability to pass `--features=a,b,c` to `cargo publish` for a specific package

### ISSUE THREAD

**Issue by VorpalBlade** [MarcoIeni/release-plz#1308]
## Motivations

I have a package that has selectable backends. You need to select *at least* one of them (this is enforced via the following in lib.rs:
```
#[cfg(not(any(feature = "arch_linux", feature = "debian")))]
compile_error!("At least one backend must be enabled");
```

It doesn't make sense to me to put either of these package manager backends as defaults features (I generally don't like default features, it makes crates not consider what they actually need which makes life annoying when developing embedded things due to feature unification suddenly pulling in more than is strictly needed, especially pulling in things needing std).

When publishing this crate I thus need to pass something like `--features=arch_linux,debian`. I can't see a way to do this with release-plz. Instead it seems I only have the option of `publish_no_verify`, which disable far more checks that I'd like.

- Would you like to implement this feature? [y/n]: I haven't looked at your code, if it isn't too difficult, maybe. Point me in the approximate direction for it.

## Solution

A per-package setting: `publish_features = ["a", "b", "c"]` 

## Alternatives

`publish_no_verify` as I said above, but it disables far more.

## Additional context

My repo is here: https://github.com/VorpalBlade/paketkoll (this is the first time I'm maintaining a public workspace with multiple crates, and the first time I'm trying out release-plz (not yet pushed that integration)).

**Comment by MarcoIeni** [comment]
This is a good addition, yes 👍
If you want to work on it, you can follow the flow of the no-verify flag you mentioned

**Comment by VorpalBlade** [comment]
Took a look at this today and it seems reasonably easy. How should inheriting the feature from the global config to per-crate be handled though? Additive or replacement? I'm leaning towards replacement.

**Comment by MarcoIeni** [comment]
Closed by https://github.com/MarcoIeni/release-plz/pull/1320 

Thanks! 🙏
