### ISSUE TITLE
release-plz doesn't find changes in README for virtual workspace

### ISSUE THREAD

**Issue by VorpalBlade** [MarcoIeni/release-plz#1309]
## Bug description

I'm using a cargo [virtual workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace). That is, there is no package in the root of the workspace. However I have a README in the root of the workspace (since that is the landing page on github). For the bin package I use that as the readme in Cargo.toml:

```toml
[package]
# ...
readme = "../../README.md"
# ...
```

When release-plz generates the changelog it doesn't seem to add `doc:` fixes to this README.md to the changelog of that package

- Would you like to work on a fix? [y/n] This is going to be complicated due to assumptions isn't it? If so, nah!

## To Reproduce

1. git clone https://github.com/VorpalBlade/paketkoll
2. cd paketkoll
3. git checkout 416599323b5a9721d05860b34755d1990131c762
4. release-plz update

## Expected behavior

Note that many doc changes end up missing from the paketkoll readme. One of them seem to be included.

## Environment

- OS: Arch Linux
- release-plz version: 0.3.48 (cargo install)

**Comment by MarcoIeni** [comment]
oh, you are right, thanks.

The issue is that we are using `cargo package --list` to determine what files should we consider, and this is the output of the command:

```
$ cargo package --list -p paketkoll
.cargo_vcs_info.json
CHANGELOG.md
Cargo.lock
Cargo.toml
Cargo.toml.orig
README.md
build.rs
src/cli.rs
src/main.rs
```

The solution is to read the `readme` field from cargo metadata.
