### ISSUE TITLE
Workspace releases all packages

### ISSUE THREAD

**Issue by baszalmstra** [MarcoIeni/release-plz#1311]
## Bug description

I am working with a repository that contains several crates in [a single workspace](https://github.com/mamba-org/rattler). I would expect if a change happens to one of the packages that only that package should have to be released.

See [this PR created by release-plz ](https://github.com/mamba-org/rattler/pull/542) that shows some undesired behavior:
1. All crates in the workspace are bumped, even if there are no changes in the crate.
2. Some changes do not affect the code at all, (moving dependencies from workspace to individual crates) but the crates are still bumped.

I understand that if other crates depend on that crate they might also require a bump. But if the changed crate's version would still satisfy the dependants requirement I don't think a bump is required.

- Would you like to work on a fix? Sure! 

## To Reproduce

1. Take this repository: https://github.com/mamba-org/rattler
2. Run `release-plz update` and notice that all crates are updated.

## Expected behavior

I would only expect a version bump for creates that:
1. have code changes (Basically the crates that also show API compatible changes).
2. depend on other workspace crates that just received an incompatible bump.

**Comment by MarcoIeni** [comment]
Release-plz force-pushed the release pr 15 minutes after you opened this issue.
I can't reproduce this bug.
Also `rattler` is a big repository.

Please, submit:
- commit in the history where I should run `release-plz update`
- why the actual `release-plz update` output is wrong
- expected `release-plz update` output (changed Cargo.toml and changelog)

It's even better if you manage to reproduce your issues in a smaller repository (maybe a toy repo you created just for reproducing release-plz issues)!

**Comment by baszalmstra** [comment]
Hey @MarcoIeni, sorry I should have been more clear:

* The hash to use is: https://github.com/mamba-org/rattler/commit/82dc20fde1c4f2c57748ffdd493784fe3d98e599
* When I run `release-plz` I get the following output:

```
* `rattler`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_conda_types`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_digest`: 0.19.0 -> 0.19.1
* `rattler_macros`: 0.19.0 -> 0.19.1
* `rattler_package_streaming`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_networking`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_lock`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_repodata_gateway`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_solve`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_libsolv_c`: 0.19.0 -> 0.19.1
* `rattler_virtual_packages`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_index`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `rattler_shell`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
```

release-plz seems to bump certain packages that haven't changed at all or are still compatible with some of the changes. Note for instance the package `rattler_macros`. I also noted in the logs:

```
 2024-02-29T09:11:23.836209Z  INFO  rattler_macros: already up to date
 ```
 
 I would expect release plz not to bump any of those crates.

**Comment by MarcoIeni** [comment]
The pr body shows the `rattler_macros` crate update (i.e. `rattler_macros: 0.19.0 -> 0.19.1` because it has the `version.workspace = true` in Cargo.toml, but if you look at the changed files, `rattler_macros` doesn't contain any changes.
However, when you merge the PR, the new version of `rattler_macros` will be published, because `version.workspace` changed. So I think it makes sense that it appears in the PR body.

**Comment by baszalmstra** [comment]
🤦

Thank you for debugging this.
