### ISSUE TITLE
Dev dependency not released in order

### ISSUE THREAD

**Issue by sd2k** [MarcoIeni/release-plz#1316]
## Bug description

I have a possibly unusual situation where my workspace contains a crate which is only ever used as a dev-dependency, but should still be released and published. I think `release-plz` should handle this correctly but for some reason I'm seeing this issue on every release.

My crates' dependency graph (including dev dependencies) looks something like:

- augurs-core
- augurs-ets
  - augurs-core
  - augurs-mstl
  [dev-dependencies]
  - augurs-testing
- augurs-mstl
  - augurs-core
  [dev-dependencies]
  - augurs-testing
- augurs-seasons
  [dev-dependencies]
  - augurs-testing
- augurs-testing

For [this release PR](https://github.com/grafana/augurs/pull/64) I expected `augurs-core` and `augurs-testing` to be released first, then `augurs-mstl` and `augurs-seasons`, and finally `augurs-ets`. The [release pipeline](https://github.com/grafana/augurs/actions/runs/7976776252/job/21778113330), however, attempted to release `augurs-mstl` before `augurs-testing`, which obviously failed because there was no matching version on crates.io.

Once I released augurs-testing manually, 

I wonder if this is related to it being a dev dependency, or because it's specified as a workspace dependency (it's in `[workspace.dependencies]` as `augurs-testing = { version = "0.1.2", path = "crates/augurs-testing" }`, and other crates depend on it as `augurs-testing.workspace = true`), or some interaction between the two?

- Would you like to work on a fix? y

## To Reproduce

Hmm, not certain but I think a similar setup to above would do it? Possibly just a 2-crate workspace with one crate _only_ being required as a dev dependency?

## Expected behavior

Dependencies should be released in the correct order.

## Screenshots

N/A

## Environment

- OS: GitHub runner, `ubuntu-latest`
- release-plz version: latest, I think - it's using the GitHub action.

## Additional context

- [Release PR](https://github.com/grafana/augurs/pull/64)
- [Failing CI run](https://github.com/grafana/augurs/actions/runs/7976776252/job/21778113330)
- [Successful CI run](https://github.com/grafana/augurs/actions/runs/7976776252/job/21778591086)
- [workspace Cargo.toml](https://github.com/grafana/augurs/blob/main/Cargo.toml)

**Comment by sd2k** [comment]
OK I can see that this is intentional according to the [`should_dep_be_released_before` function](https://github.com/sd2k/release-plz/blob/d4325dd552af3e38203e9acaa27b7a1a3c9e118a/crates/release_plz_core/src/release_order.rs#L79), I guess because it helps support circular dependencies. I think I _could_ workaround by adding a dummy `all` feature to my dev dep package and a dummy `dev = ["dev/all"]` feature to my non-dev packages but that feels pretty hacky 🤔

**Comment by MarcoIeni** [comment]
> I guess because it helps support circular dependencies

Yes, I think this was why I implemented it this way!
I'm curious in what order [cargo-release](https://github.com/crate-ci/cargo-release) would release your dependencies.

Anyway, why do you need to release `augurs-testing`? If it is only used inside the workspace, you don't need to!
Just specify the path, like I do [here](https://github.com/MarcoIeni/release-plz/blob/93d1e72a89d34cb07f8f0a656155d71f2511e5d4/crates/release_plz/Cargo.toml#L52) instead of specifying a version too.

As an alternative (if you really want to publish the augurs-testing crate, you can run `release-plz release -p augurs-testing` before running `release-plz release` in CI. However the option `release-plz release -p` is not present in the release command, so we would need to implement this first.

**Comment by sd2k** [comment]
> Anyway, why do you need to release augurs-testing? If it is only used inside the workspace, you don't need to!
Just specify the path, like I do [here](https://github.com/MarcoIeni/release-plz/blob/93d1e72a89d34cb07f8f0a656155d71f2511e5d4/crates/release_plz/Cargo.toml#L52) instead of specifying a version too. You can do it also in the workspace Cargo.toml I think.

😲 I didn't even think of that! Indeed I don't need to publish it, I probably just copied and pasted the version from all the other dependencies 🤦 that's a great solution for my case at least, no need for the extra flag. Thanks a lot!

**Comment by MarcoIeni** [comment]
No worries and thanks for the donation ❤️
Also I'm a huge grafana fan. 🙏
