### ISSUE TITLE
Change the flag `--project-manifest` to `--manifest-path`

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1333]
This is because the `--manifest-path` flag also exists in `cargo`.

Keep the old flag for cli retro-compatibility, but hide it from the help menu.

- [x] also update the github action input parameter
- [x] also update any occurrence of `--project-manifest` in the codebase (e.g. in error messages)

**Comment by amartyadav** [comment]
Hi @MarcoIeni, I would like to implement this, and I have started working on it. 

I have a couple of questions to clarify - 
- when you say "Keep the old flag for cli retro-compatibility, but hide it from the help menu", do you want me to just comment out the old flag, and add the new oe instead?
- I am assuming you do not want any refactoring of functions to follow the --manifest-path name, right? for eg. 
`fn optional_project_manifest(&self) -> Option<&Utf8Path>` should remain the same and not be changed to 
`fn optional_manifest_path(&self) -> Option<&Utf8Path> `. Am I correct to assume this?

**Comment by amartyadav** [comment]
Addressed this issue in PR #1390. @MarcoIeni , please have a look whenever you can. Cheers! 😇

**Comment by MarcoIeni** [comment]
I don't think it's needed to refactor the functions, yes 👍
