### ISSUE TITLE
Failed to update workspace packages

### ISSUE THREAD

**Issue by orhun** [MarcoIeni/release-plz#1360]
## Bug description

In my [daktilo project](https://github.com/orhun/daktilo) I switched to workspaces ([split the crate into 2 crates](https://github.com/orhun/daktilo/pull/66)) and now `release-plz` errors with:

```
     Updating crates.io index
note: Downloading daktilo 0.5.0
 Downloading crates ...
  Downloaded daktilo v0.5.0
note: Cloning into "/tmp/.tmpUPqxNn"
  2024-03-24T13:37:32.693781Z  WARN  Package `daktilo_lib@*.*.*` not found
    in download with self=PackageDownloader { packages: ["daktilo", "daktilo_lib"], directory: "/tmp/.tmpUPqxNn", registry: None, cargo_cwd: None }
    in next_versions
    in update
    in release_pr

  2024-03-24T13:37:33.303035Z ERROR  failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference between packages
    2: cannot compare README files
    3: cannot determine hash of "/tmp/.tmp7VfYce/daktilo/crates/daktilo/../../README.md"
    4: No such file or directory (os error 2)

Error: failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference between packages
    2: cannot compare README files
    3: cannot determine hash of "/tmp/.tmp7VfYce/daktilo/crates/daktilo/../../README.md"
    4: No such file or directory (os error 2)
```

It might be about:

```toml
[package]
name = "daktilo"
readme.workspace = true
# <strip>
```

But I'm not sure.

- Would you like to work on a fix? - if possible

## To Reproduce

See the CI workflow: https://github.com/orhun/daktilo/blob/main/.github/workflows/cd.yml

Example run: https://github.com/orhun/daktilo/actions/runs/8409724309/job/23027336861

## Expected behavior

No errors.

## Environment

- OS: GitHub Actions (ubuntu)
- release-plz version: `MarcoIeni/release-plz-action@v0.5`

## Additional context

None.

**Comment by MarcoIeni** [comment]
something bad is going on [here](https://github.com/MarcoIeni/release-plz/blob/7a7fb5f9c31f06f32a49794cf9e761df33f8d4c6/crates/release_plz_core/src/package_compare.rs#L148).

Possible solutions:
- return true if `local_package_readme_path` doesn't exist. Not sure if this is the correct thing to do.
- return true if `cannot compare README files` and emit a warning. Probably this is the best short-term solution, so we fix this bug soon. In the next weeks I'll try to understand what's the real bug. Do you want to submit a PR with this fix?

**Comment by MarcoIeni** [comment]
Also, this code was introduced in [0.3.51](https://github.com/MarcoIeni/release-plz/blob/main/CHANGELOG.md#0351---2024-03-08) so maybe you can use version [v0.5.44](https://github.com/MarcoIeni/release-plz-action/releases/tag/v0.5.44) of the action: `MarcoIeni/release-plz-action@v0.5.44` as a temporary workaround

**Comment by orhun** [comment]
Hey, I'm happy to work on it but unfortunately I couldn't reproduce this locally. I've tested the latest master and `release` subcommand worked fine :/

Using `MarcoIeni/release-plz-action@v0.5.44` seems like it will work, but I hit another issue.

> https://github.com/orhun/daktilo/actions/runs/8411834568/job/23031905810

I am embedding some folders into the binary and `release-plz` looks for the wrong path for them. So I patched it in the workflow [in this commit](https://github.com/orhun/daktilo/commit/e9eafb6669d02868a1949a470cc44a7b223acccd).

But now it says that project has uncommitted changes.

> https://github.com/orhun/daktilo/actions/runs/8411897970/job/23032042405

Is there a way to pass `--dry-run` to `release-plz-action`?

**Comment by MarcoIeni** [comment]
The issue is in the `update` command, not `release`

**Comment by MarcoIeni** [comment]
> Is there a way to pass --dry-run to release-plz-action?

You can add

```
[workspace]
allow_dirty = true
```

to the config file

**Comment by orhun** [comment]
> allow_dirty = true

Tried this in <https://github.com/orhun/daktilo/commit/1fba8edbf4b105c5a1f3e7b379d8a3b64c5bb932>

But it didn't work:

```
error: 1 files in the working directory contain changes that were not yet committed into git:
src/embed.rs
to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag
```

<https://github.com/orhun/daktilo/actions/runs/8426534601/job/23075046031>

**Comment by Boshen** [comment]
I'm also facing this issue, and here's an observation:

```
note: Cloning into "/tmp/.tmpUPqxNn"

    3: cannot determine hash of "/tmp/.tmp7VfYce/daktilo/crates/daktilo/../../README.md"
```

Notice these two tmp folders are different :-)

**Comment by MarcoIeni** [comment]
Sorry about it, I will try to fix this in the following days

**Comment by Boshen** [comment]
@MarcoIeni If you need a reproduction:

https://github.com/boshen/criterion2.rs

```
criterion2.rs  main ❯ ~/.cargo/bin/cargo-release-plz update
  2024-04-02T08:09:31.952062Z  INFO  using release-plz config file release-plz.toml

  2024-04-02T08:09:32.169519Z  INFO  downloading packages from cargo registry
    in download with self=PackageDownloader { packages: ["criterion2"], directory: "/var/folders/30/cmv9c_5j3mq_kthx63sb1t5c0000gn/T/.tmpehLfBs", registry: None, cargo_cwd: None }
    in next_versions
    in update

note: Cloning into "/var/folders/30/cmv9c_5j3mq_kthx63sb1t5c0000gn/T/.tmpehLfBs"
    Updating crates.io index
note: Downloading criterion2 0.6.0
  2024-04-02T08:10:11.932836Z ERROR  failed to determine next versions

Caused by:
    0: failed to retrieve difference between packages
    1: cannot compare README files
    2: cannot determine hash of "/var/folders/30/cmv9c_5j3mq_kthx63sb1t5c0000gn/T/.tmpRQERx3/criterion2.rs/README.md"
    3: No such file or directory (os error 2)

Error: failed to determine next versions

Caused by:
    0: failed to retrieve difference between packages
    1: cannot compare README files
    2: cannot determine hash of "/var/folders/30/cmv9c_5j3mq_kthx63sb1t5c0000gn/T/.tmpRQERx3/criterion2.rs/README.md"
    3: No such file or directory (os error 2)
```

**Comment by MarcoIeni** [comment]
Your projects should now work, I'll keep this issue open, because when comparing the readme there's a bug if the README path was specified after the package was released last time.
In theory we should read the readme field from Cargo.toml at every commit.

**Comment by MarcoIeni** [comment]
I will look into this! Also, the error message you are getting now (`Is a directory (os error 21)`) is pretty bad, I'm sorry!
Maybe somewhere we are using `fs` instead of `fs_err`.
Btw, `release-plz update` works well locally for me (after running `git submodule update --init`), so maybe you can run it locally as a workaround for now :/

**Comment by Sec-ant** [comment]
> I will look into this! Hopefully I'll find some time this week.
> Also, the error message you are getting now (`Is a directory (os error 21)`) is pretty bad, I'm sorry!
> Maybe somewhere we are using `fs` instead of `fs_err`.
> Btw, `release-plz update` works well locally for me (after running `git submodule update --init`), so maybe you can run it locally as a workaround for now :/

Yes, after allowing dirty files we can run release-plz locally. But like you said it's getting the "is a directory" error when running in GitHub Actions. And I'm also curious why dirty files have to be allowed in our repo.

Thanks in advance for your work!

**Comment by MarcoIeni** [comment]
I released a new version of release-plz where I improved the error messages of the file system ( https://github.com/MarcoIeni/release-plz/pull/1450 )
Let me know if the error message `Is a directory (os error 21)` looks different next time you merge a PR 👍 
Hopefully we get more insights and find the root cause.

One more thing: are you able to reproduce the bug locally when running `release-plz release-pr --git-token XXX`?

**Comment by MarcoIeni** [comment]
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/002dc872-602b-46a6-b2a6-3b659146c6ea)
now the error is a bit better, but it's not clear why release-plz is trying to read that file. I need to add more info to the error messages.

**Comment by Sec-ant** [comment]
> ![image](https://private-user-images.githubusercontent.com/11428655/329811340-002dc872-602b-46a6-b2a6-3b659146c6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDE5NTgsIm5iZiI6MTcxNTUwMTY1OCwicGF0aCI6Ii8xMTQyODY1NS8zMjk4MTEzNDAtMDAyZGM4NzItNjAyYi00NmE2LWIyYTYtM2I2NTkxNDZjNmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA4MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYTFkOTc2MWM2ZGM1YWY4ZTY0MGE5MmI2YmE0ZjM3Mzc5MDE3ZjA0ZmJhOTQ2MGI3Y2FiZWMwNDI1NjdlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SLhDMPnPE93jJeY8otzPF_r44AIWzhqoW8R112jBKU) now the error is a bit better, but it's not clear why release-plz is trying to read that file. I need to add more info to the error messages.
> 
> EDIT: imo the error is [here](https://github.com/MarcoIeni/release-plz/pull/1455/files#diff-29866be0433903fbd11cd53630a1c03ad34a636034e83c566540cc82e300e43c) Let's see once I deploy the new release-plz :)

Thank you again for your time into debugging this ❤️. I don't know if it helps but that `tree-sitter-php` file is actually a git submodule, maybe there're some unexpected problems?

> One more thing: are you able to reproduce the bug locally when running `release-plz release-pr --git-token XXX?`

Sorry I'm just an ordinary contributor so it seems I don't have the permission to test it in that repo.

**Comment by MarcoIeni** [comment]
I see 👍
I released the new version with more error context. Let's see how the error shows.

**Comment by MarcoIeni** [comment]
I released yet another version. The release contains https://github.com/MarcoIeni/release-plz/pull/1461 which should fix gritql 👍 
So I expect the next commit they do to create a release pr 👍

**Comment by Sec-ant** [comment]
> I released yet another version. The release contains #1461 which should fix gritql 👍 So I expect the next commit they do to create a release pr 👍

A release PR is successfully created, thank you!
