### ISSUE TITLE
ERROR failed to update packages

### ISSUE THREAD

**Issue by doprz** [MarcoIeni/release-plz#1376]
## Bug description

https://github.com/pacak/cargo-show-asm/issues/259

- Would you like to work on a fix? [y/n]: Looking for help to resolve this issue.

## To Reproduce

Running `RUST_LOG=debug release-plz update` via both a GitHub Action Workflow or locally causes this error.

## Environment

`stable-x86_64-unknown-linux-gnu - rustc 1.77.1`
`MarcoIeni/release-plz-action@v0.5`
`release-plz-v0.3.56`

**Comment by MarcoIeni** [comment]
having a look 👍

**Comment by MarcoIeni** [comment]
this should be fixed. I just released a new version of release-plz and the github action.
Let me know if you still have issues 👍

**Comment by doprz** [comment]
Thank you!
