### ISSUE TITLE
release-pr rebase looses verified status

### ISSUE THREAD

**Issue by zvolin** [MarcoIeni/release-plz#1406]
## Bug description

So currently for github PR's, release plz will create the commit through github api to have the `Verified` badge. However when pulling in new changes, it rebases and pushes it using the `git` command which results in updated commit not having the verified status.

- Would you like to work on a fix? [y]

## To Reproduce

You can check eg. https://github.com/eigerco/lumina/pull/189. Currently we have to `git commit --amend --S` for each release-plz PR which was rebased by the action.

## Additional context

I've re-checked the [github API](https://docs.github.com/en/graphql/reference/mutations#createcommitonbranch) and there seems to be no way to do it via it. I can't think of any clean solution right now rather than opening an issue for github to add some new API to achieve that.

**Comment by MarcoIeni** [comment]
that's unfortunate :/ So in you don't have any solutions in mind on how to fix this?

**Comment by zvolin** [comment]
nope, no ideas so far

**Comment by zvolin** [comment]
one way around would be to have a way to configure release-plz to always recreate PR's, however this will likely make a loooot of noise in repos PRs...

**Comment by zvolin** [comment]
some other workaround could be to have an option like 'rebase=false' and it would create merge commits with main branch each time instead rebasing, and we could document this flag to be only used with squash-merge at the end, cleaning up the resulting message (if github happens to include those merge commits in squashed message)

**Comment by zvolin** [comment]
the only clean way seems to be get new api into github

**Comment by MarcoIeni** [comment]
> one way around would be to have a way to configure release-plz to always recreate PR's, however this will likely make a loooot of noise in repos PRs...

This was the original implementation. It makes a lot of noise, yes.

**Comment by MarcoIeni** [comment]
> some other workaround could be to have an option like 'rebase=false' and it would create merge commits with main branch each time instead rebasing, and we could document this flag to be only used with squash-merge at the end, cleaning up the resulting message (if github happens to include those merge commits in squashed message)

I think sometimes you would encounter git conflicts in this way :(

**Comment by Pr0methean** [comment]
The noise could be reduced by rate-limiting the PR recreations and scheduling the postponed ones to happen at troughs of activity, at least for teams that have predictable troughs (mostly in a narrow range of time zones , or low activity on weekends).

**Comment by MarcoIeni** [comment]
You can already customize how to run the action. Example [here](https://release-plz.ieni.dev/docs/github/quickstart#example-release-pr-and-release-on-schedule) 👍

**Comment by Pr0methean** [comment]
Right, but what I mean is that implementing the always-recreate option wouldn't create unacceptable noise for teams that did so.

**Comment by MarcoIeni** [comment]
I documented how to close the old pr by yourself in https://github.com/MarcoIeni/release-plz/pull/1452

If there are no PRs, release-plz will always open a new one :)
I haven't fully tested it.
Can you give it a try and let me know if it works? Then I'll merge it 👍

**Comment by Pr0methean** [comment]
Looks mostly good, but what happens if there *isn't* already an open PR?

**Comment by MarcoIeni** [comment]
Thanks, merged it!

Of course I'll leave this issue open because ideally we want the release-plz force-push to keep the verified status 👍

**Comment by MarcoIeni** [comment]
What if we do:

```
git reset --hard HEAD~1
git push --force 
commit via github api
```

could it work?

**Comment by zvolin** [comment]
I don't think if this would work, iirc you must provide the hash of the commit that you want to be a parent manually and just send changed files. What you do with git locally doesn't matter to the API. I bet if you would provide incorrect parent, it will just fail the api call

**Comment by zvolin** [comment]
wait, I think I didn't understand, this may indeed work!

**Comment by MarcoIeni** [comment]
That's great 🥳
Do you want to open a pr?

**Comment by zvolin** [comment]
Sure :)

**Comment by MarcoIeni** [comment]
Your solution is even simpler than my idea 🙌
Thank you for the PR ❤️

**Comment by zvolin** [comment]
it's basically your idea just all the pieces were already there :d

**Comment by MarcoIeni** [comment]
Yeah, I thought a `git reset --hard HEAD~1` was necessary but it was indeed done earlier 👍
