### ISSUE TITLE
Misconfigured log level?

### ISSUE THREAD

**Issue by LukeMathWalker** [MarcoIeni/release-plz#1409]
## Bug description

`release-plz` adds an `ERROR` prefix to log lines that are clearly... not errors?

## To Reproduce

See [this CI run](https://github.com/LukeMathWalker/pavex/actions/runs/8771457352/job/24069249151), under "Run release-plz".
Example:
<img width="814" alt="immagine" src="https://github.com/MarcoIeni/release-plz/assets/20745048/6fc3bc9d-f864-420f-8735-95698034303d">

**Comment by MarcoIeni** [comment]
I fixed this recently, today I will release a new version 👍
