### ISSUE TITLE
What if a release PR goes out of date while in a merge queue?

### ISSUE THREAD

**Issue by Pr0methean** [MarcoIeni/release-plz#1412]
## Motivations
I'm planning to move https://github.com/Pr0methean/zip to the `zip-rs` org as soon as I can get the permission, and then enable a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue). However, it occurs to me that a release PR will release the changes that were in the queue when it was opened, and changes that were in the same `merge_group`, without updating the CHANGELOG to mention them. Also, if a patch release queues behind a breaking change, the semver will falsely indicate it's backward-compatible.

- Would you like to implement this feature? y

## Solution

One solution would be to store the commit hash for each push of a release PR, and add an `on: merge_group` CI check that would fail the build if the commit hash it was building against was different. However, we'd also need a way to prevent release PRs from being grouped with other PRs on the initial attempt, in case that attempt took long enough that another `merge_group` was always merged while it was waiting.
## Alternatives

Another option would be to use a CI check and some sort of shared variable to disable merges of non-release PRs while a release PR was in the queue.

**Comment by MarcoIeni** [comment]
Hi! I know the concept of merge queues, but I never used them.
Is the problem you described similar to https://github.com/MarcoIeni/release-plz/issues/1030 ?

**Comment by Pr0methean** [comment]
Yes; it looks to be the same issue (although nobody there has pointed out how much more important semvers are than CHANGELOGs).

**Comment by MarcoIeni** [comment]
ok, I'll close this then. We can continue the discussion in that one 👍
