### ISSUE TITLE
allow to modify the logic of next_version to add more prefixes that will bump versions

### ISSUE THREAD

**Issue by MeitarR** [MarcoIeni/release-plz#1510]
## Motivations

Our project uses conventional commits, and with git-cliff, it's awesome. now we added a new prefix (let's say `abc`) that should also bump the minor (and it makes sense in the context of the repo).

now we can't do that because it's hard coded in the repo that only feat and breaking change will bump the minor.

- Would you like to implement this feature? maybe

## Solution

I can see how it can be solved by receiving a regex for major and minor that will check against the `Custom` [conventional_commit_parser](https://docs.rs/conventional_commit_parser/latest/conventional_commit_parser/index.html)::[commit](https://docs.rs/conventional_commit_parser/latest/conventional_commit_parser/commit/index.html)::[CommitType](https://docs.rs/conventional_commit_parser/latest/conventional_commit_parser/commit/enum.CommitType.html#)

## Additional context

I would like this so git-cliff will be able to configure the regex from its config and then I could use it in my repo to release and bump automatically

**Comment by MarcoIeni** [comment]
PR welcome 👍 Please add tests, too.
