### ISSUE TITLE
GitHub action creates release immediately when commiting workflow to repo

### ISSUE THREAD

**Issue by avsaase** [MarcoIeni/release-plz#1541]
## Bug description

When committing the GitHub action workflow file to the `master` branch the action immediately creates a new release. This happened to me in two different projects when settings up release-plz. In both cases the project did not previously have a release on crates.io but I'm not sure if that's relevant.

- Would you like to work on a fix? N

## To Reproduce

1. Commit the release-plz workflow file to the `master` branch.
2. A release PR is created and the crates are released on crates.io

## Expected behavior

A release should only be created after the release PR is merged.

## Screenshots

One repo where this problem occurred is [avsaase/imu-fusion](https://github.com/avsaase). I added the workflow file in https://github.com/avsaase/fusion-imu/commit/fa46cb1c185032b551987892f2e7ebc050737339 but had some problems generating the token for my GitHub App. I switched to another action in https://github.com/avsaase/fusion-imu/commit/792d20bac2653ab6213b8a489c5155e9cbc0feed so this is the first successful workflow run: https://github.com/avsaase/fusion-imu/actions/runs/9814346606. In this case I had an invalid category configured in my `Cargo.toml`s so crates.io rejected the releases.

## Environment

- OS: [e.g. Ubuntu 20.04] N/A
- release-plz version: [e.g. 0.1.0] `86afd21a7b114234aab55ba0005eed52f77d89e4`

## Additional context

Thanks for making this awesome tool!

**Comment by avsaase** [comment]
I see now that the action tries to publish the release on every new push to the `master` branch, while the release PR (https://github.com/avsaase/fusion-imu/pull/1) is not merged yet.

**Comment by avsaase** [comment]
Looking through the config options I see `release_always`. Setting is to false should do what I want. I'm a little confused what the intended default workflow is though. Is the idea to publish to crates.io for every push to master and merge the release PR after the fact?

**Comment by MarcoIeni** [comment]
This is the intended behavior. Release-plz always publish to the cargo registry. 
When you merge the release pr, release-plz publishes the new changes. But in theory you can also edit cargo.toml by yourself 👍

If you only want to merge when you merge the release pr, there's the config option you mentioned 👍

**Comment by avsaase** [comment]
Do you mean that _every commit_ to the base branch by default is published as a release? If so then I think the documentation could be improved to make this more explicit.

**Comment by MarcoIeni** [comment]
Yes. But a crate is published only if the cargo.toml version changes to a version that isn't present in the cargo registry.

Documentation pr welcome 🙏

**Comment by avsaase** [comment]
Aaaah, that's the part I was missing. Thanks for clarifying.

To summarize, the workflow is like this:
1. Commit changes to `master`.
2. A release PR is openend.
3. Change is not yet released because the version is the same as what has been published previously.
4. Merge the release PR that changes the version so that it will now make the release.

In practice this is the same as when setting 
`release_always = false` except when the crate has never been published and you can't manually trigger a release by changing the version.

If that's correct I'll try to make a doc PR to make this more clear.

**Comment by MarcoIeni** [comment]
Yes, that's correct 👍
