### ISSUE TITLE
release-plz fails to release root crate

### ISSUE THREAD

**Issue by BobG1983** [MarcoIeni/release-plz#1545]
## Bug description
Running release-plz release on my crate https://github.com/BobG1983/rantz_suite succesfully updates, PRs, and releases the crates in the workspace, and will update the root crate, but will fail to release with failed to publish rantz_suite: error: the `-p` argument must be specified to select a single package to publish

## To Reproduce

Fork my crate.
Change the crate name.
Setup releaze-plz.
Cargo publish the crate
Make a change
Run release-plz

## Expected behavior

Version number of sub-crates is bumped as appropriate
Version number of root crate is bumped as appropriate
Sub-crates are published
root-crate is published

## Environment

Windows Nightly, but also Ubuntu-Latest on Github CI

## Additional context

I'm possibly doing something dumb. halp

**Comment by BobG1983** [comment]
Fixed it I think in my local branch by not having a "root crate" but still

**Comment by MarcoIeni** [comment]
Thanks for opening this issue.
I got back in the git history of your project.
`cargo +nightly publish --dry-run --manifest-path Cargo.toml` fails with the error release-plz reports. However adding `-p rantz_suite` works.

So I'm adding the `-p` flag to make the publish workflow more robust in https://github.com/MarcoIeni/release-plz/pull/1560

- Can you test this locally by running `release-plz release`?

If it works for you and the change looks good to you (i.e. no use cases that could be broken by this comes to your mind) we can merge it 👍
