### ISSUE TITLE
Consistent version across entire workspace

### ISSUE THREAD

**Issue by mattstam** [MarcoIeni/release-plz#1557]
## Motivations

Currently, if you have a workspace with many crates, even if you start each crate off at the same version (e.g. `v0.1.0`), their versions will slowly diverge overtime. 

The primary reason this seems to happen in when one crate (`crate-a`) has a breaking change when another crate (`crate-b`) does not, for example `crate-a` goes to `v0.2.0` while `crate-b` goes to `v0.1.1`. Another reason is simply that one of the crates has not been updated since last release, and therefor release-plz doesn't detech any change.

## Solution

It would be great if every single crate in the workspace would all stay on the same version, even if they haven't been changed. Optionally: it should just match the highest required version bump. In the above case, both `crate-a` and `crate-b` would go to `v0.2.0`.

## Alternatives

Also open to other options, maybe something like this can already be enabled by using the existing features?

**Comment by MarcoIeni** [comment]
Release-plz supports cargo workspace versions.

https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

Write the version in the main cargo.toml and inherit it in the other cargo.toml by specifying `version.workspace = true`
