### ISSUE TITLE
Creating GitHub Release fails

### ISSUE THREAD

**Issue by TerakomariGandesblood** [MarcoIeni/release-plz#1592]
## Bug description

I encountered an error when creating a GitHub Release using release-plz in GitHub Action

> ERROR  failed to release package
> Caused by:
>    0: Failed to create release
>    1: HTTP status client error (422 Unprocessable Entity) for url (https://api.github.com/repos/novel-rs/opencc-rs/releases)

https://github.com/novel-rs/opencc-rs/actions/runs/10263182078/job/28394424878

## To Reproduce

1. Merge release pr
2. As you can see, the cargo publish succeeds, but creating the GitHub Release fails!

## Expected behavior

GitHub Release created successfully

## Screenshots

<img width="771" alt="image" src="https://github.com/user-attachments/assets/0148c5ac-f39b-4e85-96d5-930c48375b5d">

## Environment

- OS: Ubuntu 22.04
- release-plz version: 0.3.81

**Comment by MarcoIeni** [comment]
Closed by https://github.com/MarcoIeni/release-plz/pull/1594

Sorry 😅

**Comment by jdrouet** [comment]
Thanks a lot!
