### ISSUE TITLE
Major release of dependencies does not propagate to dependents which use it as a public type

### ISSUE THREAD

**Issue by NobodyXu** [MarcoIeni/release-plz#1599]
## Bug description

In cargo-bins/cargo-binstall#1870 , binstalk-type is bumped to 0.9.

Since binstalk-types is used in other binstalk-* crates as dependencies, I'd expect them to bumped to next
major version as well, but release-plz only bumps another patch release.

- Would you like to work on a fix? n

## To Reproduce

cargo-bins/cargo-binstall#1870

## Expected behavior

release-plz should bump dependents to next major versions as well.

**Comment by NobodyXu** [comment]
Honestly I'm not sure how to fix this, it sounds like something that requires a lot parsing like `cargo-semver-checks` does, to query to public type used in it (or using generated docs)

**Comment by MarcoIeni** [comment]
Yeah, release-plz doesn't introspect code to check these kind of changes, I think this is something that needs to be addressed in `cargo-semver-checks`.
If I understood well, they are working to support this, but I'm not certain.

Please, re-open if you feel like we still need to discuss something 👍
