### ISSUE TITLE
Hazard - failing release means future release notes don't get generated

### ISSUE THREAD

**Issue by joshka** [MarcoIeni/release-plz#1601]
## Bug description

This might be the same issue as https://github.com/MarcoIeni/release-plz/issues/1539, I'm' not entirely sure.

https://github.com/joshka/tui-widgets/pull/23 was a release pr, which failed to release ([workflow log](https://github.com/joshka/tui-widgets/actions/runs/10260378513/job/28386340627)) with the following issue:

```
  2024-08-06T04:41:42.169738Z  INFO  using release-plz config file release-plz.toml

  2024-08-06T04:42:29.410572Z ERROR  failed to release package

Caused by:
    0: Failed to create release
    1: HTTP status client error (422 Unprocessable Entity) for url (https://api.github.com/repos/joshka/tui-widgets/releases)

Error: failed to release package

Caused by:
    0: Failed to create release
    1: HTTP status client error (422 Unprocessable Entity) for url (https://api.github.com/repos/joshka/tui-widgets/releases)
Error: Process completed with exit code 1.
```
My guess is that this was possibly caused by the consolidation of several repos (into tui-widgets ...), while leaving the previous releases in their own repos (e.g. tui-popup), and so the first release had no github release history.

There was no notification of this failing - I'd guess that the github action probably should re-open the PR and add a comment on failure at a minimum here.

---

Next, I made some changes to a dependency that affected the 5 packages in the repo. 4 of which got published without regenerating the changelog (that's the bug / problem mentioned above in #1539), and one got a changelog PR.
https://github.com/joshka/tui-widgets/actions/runs/10313294100/job/28549824151 is the log of that one

So I think there's 3 bugs (or weird behaviors at least):
- failure to publish when theirs no github release history
- automatically publishing without updating changelog of failed release with new changes
- not generating changelog for new changes

- Would you like to work on a fix? [y/n] yes, but at a low priority

I'm mostly noting this bug for describing the sequence of events that can lead to weird publishing happening. Fixing this is likely a bit of a complex task I'd guess, as it's dealing with the failure modes of several pieces.

## To Reproduce

1. ...
2. ...
3. ...
4. ...

## Environment

- OS: [e.g. Ubuntu 20.04]
- release-plz version: [e.g. 0.1.0]

**Comment by TerakomariGandesblood** [comment]
#1592 Should be the same error, I'm guessing.

**Comment by joshka** [comment]
Yep - thanks, I missed seeing that because it was closed. I think this probably still stands alone as not quite a duplicate, as the combination of errors is the interesting bit here I think. Any future publish failure would have the same net effect of missing changelog generation if a future release happens.

**Comment by MarcoIeni** [comment]
> There was no notification of this failing

The workflow fails. You can use GitHub to be notified when a workflow fails. E.g. I receive emails.

> automatically publishing without updating changelog of failed release with new changes

The release is going to retry on the next commit on main or you can manually retry it from github actions 👍

> I'd guess that the github action probably should re-open the PR and add a comment on failure at a minimum here.

I can't re-open the PR because there's not diff with main to see.

> failure to publish when theirs no github release history

This means release-plz shouldn't work on new projects, but I haven't received similar complaints so probably this is related to https://github.com/MarcoIeni/release-plz/issues/1592 which we fixed.


I'm closing this issue because I think we addressed everything and I want to keep the issue tracker clean, but please open a new issue if there's something from this issue I haven't addressed 👍
