### ISSUE TITLE
bug: {{ commit.author.name }} not working

### ISSUE THREAD

**Issue by gacallea** [MarcoIeni/release-plz#1604]
## Bug description

`{{ commit.author.name }}` not working in `{% macro print_commit(commit) -%}` 

- Would you like to work on a fix? [n]
- I wish I could but I am still studying The Book. Pretty n00b still. If you think I could try even at this level, I'd be happy to help!

## To Reproduce

1. Given [this template](https://github.com/gacallea/freesound-credits/blob/main/release-plz.toml) - (btw I want to contribute a PR for this template once we fixed this very issue)
2. Given [this cliff.toml](https://gist.github.com/gacallea/d42949306eb7855e8d661baace32a45d) - (this is just for manual testing/comparison, not used by release-plz in the end)
3. Given an existing commit history.
5. run `git cliff -o CHANGELOG.md` to fill the file a first time
6. make some commits just to test the next step
7. run `release-plz update` and see that under Unreleased the author is missing (line ending with `by` on its own)

## Expected behavior

each commit should end with an author. e.g: `Adding pre-commit hook for convetional - (924c906) by gacallea`

## Screenshots

0.2.12 by [release-plz GitHub Action](https://github.com/gacallea/freesound-credits/blob/main/.github/workflows/release-plz.yml)
0.2.11 and below generated by `git cliff -o CHANGELOG.md` with the process described in the steps above

<img width="705" alt="Screenshot 2024-08-09 at 10 22 47 PM" src="https://github.com/user-attachments/assets/842b1ec2-fe44-4afc-8b23-bbf19eedee2e">

## Environment

- OS: macOS Sonoma 14.6
- release-plz version:  0.3.83

## Additional context

Please ignore the quirks of the `cliff.toml` -- namely the broken rewrites and broken links -- as they are irrelevant here.

**Comment by MarcoIeni** [comment]
This feature is missing. It's not a bug.
https://github.com/MarcoIeni/release-plz/issues/989

**Comment by gacallea** [comment]
Sorry about the bug report then! Thank you for release-plz. <3

**Comment by MarcoIeni** [comment]
No worries 😁

**Comment by gacallea** [comment]
one question @MarcoIeni: do you like the template at all? should I PR? (ofc minus the broken stuff, which I am removing as we speak). ref: https://github.com/gacallea/freesound-credits/blob/main/CHANGELOG.md

**Comment by MarcoIeni** [comment]
Sure, the template looks dope! 🙌
Feel free to write your `[changelog]` section in the website 👍 
Instead of the macro `remote_url()` you can use `remote.link`. 👍

**Comment by MarcoIeni** [comment]
working on this here: https://github.com/MarcoIeni/release-plz/pull/1606

**Comment by gacallea** [comment]
Yay! will do as soon as I am done fixing stuff :)

To be fair: I based it on git-cliff changelog and fixed/added a few things to make it behave with markdownlint (extra spaces, h1 header) and filtered out some others.

One more thing, before I open another useless bug! I noticed that release-plz needs an extra `v` in place here, to match the same behavior in changelog:

- `({{ remote.link }}/compare/v{{ previous.version }}..v{{ version }})` -- plz
- `({{ remote.link }}/compare/{ previous.version }}..{{ version }})` -- cliff

I tried looking at the code but I am a noob. I deduced that release-plz may not be using cliff api tho and some things diverge. Is this extra v a bug I should report?

**Comment by MarcoIeni** [comment]
I didn't get the v issue. However, release-plz offers the release_link variable. Check it out in the docs. It does what you are trying to do for you 👍

We use git cliff api, but we diverge a bit, yes

**Comment by gacallea** [comment]
amazing Marco! works perfectly now :)

I also modified the example PR https://github.com/MarcoIeni/release-plz/pull/1607 to match

**Comment by MarcoIeni** [comment]
FYI commit.author.name should work now :)
just wait for CI to finish in https://github.com/MarcoIeni/release-plz/commit/4e33fe15a66714800b84ea177dc4beb350713a18
