### ISSUE TITLE
handle generation of README.md with cargo-readme

### ISSUE THREAD

**Issue by gwen-lg** [MarcoIeni/release-plz#1609]
## Motivations

I use `cargo-readme` for some of my project to automatically update the file `README.md` with version number of the crate.
But when I tried to used `release-plz` on same crate, the file `README.md` is not updated when `package.version` value is updated in `Cargo.toml`. So I need to manually run the command `cargo readme > README.md` after running `release-plz update` 

- Would you like to implement this feature? yes why not is someone can indicate me how to start

## Solution

I like, than running the command `release-plz update` also run `cargo readme > README.md` when functionality enabled.

## Alternatives

_No_

## Additional context

_No_

**Comment by MarcoIeni** [comment]
Hi!
I think it's reasonable that people want to use other commands after running release-plz. Integrating all of them would be a mess. Very hard to maintain. 

I want to make it easy to run any command after release-plz, not only cargo readme.

What's stopping you from creating a script or a shell alias that run both release-plz and cargo-readme? Is there a release-plz feature you are missing?

**Comment by gwen-lg** [comment]
Ok, it make sense.
I this case, how it can integrate with github action than generate a PR ?
Simply run a step `cargo readme` after the `MarcoIeni/release-plz-action@v0.5` one include change from cargo readme in PR ?
(I'm not familiar with how github action work).

**Comment by gwen-lg** [comment]
I have tried to add a run of `cargo readme` in the github action, but the automatic PR doesn't contain the updated `README.md`
Test branch is : https://github.com/gwen-lg/subtile/blob/test_cargo_readme/.github/workflows/release-plz.yml
Generated PR : https://github.com/gwen-lg/subtile/pull/9

Without managing `cargo readme` in a hardcoded way, `release-plz` could have a way to setup custom cargo command ?

**Comment by MarcoIeni** [comment]
You need to commit and push the generated file.
I'm on mobile, that's the best suggestion I have now, sorry!

**Comment by MarcoIeni** [comment]
I documented how to commit files in #1626 👍

**Comment by gwen-lg** [comment]
After fix problem by forget to add the line ` id: release-plz` and some adjustment, it's work.
Thank you :+1:
