### ISSUE TITLE
Allow suppressing the changelog header

### ISSUE THREAD

**Issue by tgross35** [MarcoIeni/release-plz#1620]
## Motivations

By default, the changelog has this header:

```md
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
```

The descriptions may not be accurate for some projects, and has information that is somewhat self-explanatory.

## Solution

Add an easy way to disable the header, like with a `default_header = false` setting in `[changelog]`

## Alternatives

This is possible with a custom template, but having an easy way to disable it would be nice.

**Comment by MarcoIeni** [comment]
Can't you set https://release-plz.ieni.dev/docs/config#the-header-field to ""?

**Comment by tgross35** [comment]
Oh 😆 yeah that works. Thanks!
