### ISSUE TITLE
matching release-please behaviour

### ISSUE THREAD

**Issue by danieleades** [MarcoIeni/release-plz#1631]
say I wanted to configure release-plz to have the same behaviour as release-please with respect to

- what commits generate a release PR
- what commits are included in the changelog

what configuration would i need to use for this?
Is this a common enough use-case to warrant a 'configuration profile' or an entry in the docs?

**Comment by MarcoIeni** [comment]
Which commits generate a pr: https://release-plz.ieni.dev/docs/config#the-release_commits-field

**Comment by MarcoIeni** [comment]
For the changelog there's a skip field in the commit parsers i believe. Need to check

**Comment by MarcoIeni** [comment]
Here it is https://release-plz.ieni.dev/docs/config#the-commit_parsers-field
Check the skip field 👍

**Comment by danieleades** [comment]
sorry, i think maybe you misunderstood my question.

I wasn't asking *if* it was possible, I was asking the specific configuration I would need to set in order to match it, and whether supporting that easily was a reasonable goal for this project

**Comment by MarcoIeni** [comment]
> I was asking the specific configuration I would need to set 

I linked to the relavant docs. After you read them, let me know your doubts 👍

> whether supporting that easily was a reasonable goal for this project

It's already supported
