### ISSUE TITLE
When a workspace member specifies dependencies via `member.workspace = true` the `release-plz update` does not bump the member version when the dependency is changed 

### ISSUE THREAD

**Issue by greenhat** [MarcoIeni/release-plz#1649]
In a [workspace](https://github.com/0xPolygonMiden/compiler/blob/305ea1c7724eb300c24ef8824b9c1fe9c7031780/Cargo.toml#L95-L106) where member dependencies versions are defined in the workspace Cargo.toml `[workspace.dependencies]` table via `midenc-session = { version = "0.0.5", path = "midenc-session" }` and then used in member crates via `member.workspace = true` in the `[dependencies]` in the member's Cargo.toml the `release-plz update` does not bump member versions when member dependencies versions were bumped. 

Here is the [PR](https://github.com/0xPolygonMiden/compiler/pull/294/files) where `midenc-session` version is bumped but the `miden-hir` which depends on it is not bumped.

I tried specifying a member dependency with the `version` key (i.e. `midenc-session = { version = "0.0.5", path = "midenc-session" }` in the member's crate and it worked fine.

I wonder if this happens due to this filter:
https://github.com/MarcoIeni/release-plz/blob/602e75308185d7d2246600c55b4258953e6e3b3f/crates/release_plz_core/src/next_ver.rs#L1173
that ensures that a dependency should have the `version` key to be bumped.

**Comment by MarcoIeni** [comment]
yes, you are right.
Sorry if it took so long to answer.

I refactored this function in https://github.com/MarcoIeni/release-plz/pull/1687

I'll try to fix the issue soon

**Comment by greenhat** [comment]
Thank you!

**Comment by MarcoIeni** [comment]
Sorry, I'm having another look today and it seems it's working fine.
https://github.com/MarcoIeni/rust-workspace-example/pull/215
Can you create a minimal reproduction?
You can test locally with `release-plz update`

**Comment by MarcoIeni** [comment]
# Reproduction

```toml
# Workspace Cargo.toml

[workspace.dependencies]
aaa = { path = "crates/aaa", version = "0.1.2" }
```

```toml
# Cargo.toml of bbb

[package]
name = "bbb"
version = "1.0.0"

[dependencies]
aaa.workspace = true
```

The issue is that `bbb` version is not bumped to 1.0.1 when `aaa` is updated
