### ISSUE TITLE
WARN HTTP status client error (402 Payment Required)

### ISSUE THREAD

**Issue by Veetaha** [MarcoIeni/release-plz#1650]
It took 5 minutes for release-plz to make release PR on [CI here](https://github.com/elastio/bon/actions/runs/10682927788/job/29609858971#step:4:83):

There was this warning:

```
 WARN Failed to send quickinstall report for package release-plz-0.3.85-x86_64-unknown-linux-musl: Failed to download from remote: could not HEAD https://warehouse-clerk-tmp.vercel.app/api/crate/release-plz-0.3.85-x86_64-unknown-linux-musl.tar.gz: HTTP status client error (402 Payment Required) for url (https://warehouse-clerk-tmp.vercel.app/api/crate/release-plz-0.3.85-x86_64-unknown-linux-musl.tar.gz)
```

I'm not sure if this is a temporary outage or something else. Just want to confirm

**Comment by MarcoIeni** [comment]
To fix this we need to add release-plz to https://github.com/taiki-e/install-action/blob/main/TOOLS.md

[Here](https://github.com/taiki-e/install-action/blob/main/DEVELOPMENT.md) is documented how to do it.

Do you want to give it a try? 👀

**Comment by Veetaha** [comment]
Sure, looks simple enough, I'll take try to close this one once I'm finished with https://github.com/elastio/bon/pull/99.

**Comment by Veetaha** [comment]
It should be closed by https://github.com/taiki-e/install-action/pull/649
