### ISSUE TITLE
Expose next-version's `with_features_always_increment_minor` flag

### ISSUE THREAD

**Issue by scouten-adobe** [MarcoIeni/release-plz#1656]
## Motivations

I'd like to have feature additions bump the minor version in 0.x releases. (In other words, a `feat(xyz): New stuff` commit should cause `xyz`'s version to change from 0.1.3 to 0.2.0 with this flag enabled.)

- Would you like to implement this feature? *Yes, I'd be happy to submit a PR.*

## Solution

Add a new flag to `release-plz.toml` named `features_always_increment_minor` (default = false to match existing behavior). When true, would use [`next_version::VersionUpdater:: with_features_always_increment_minor`](https://docs.rs/next_version/0.2.19/next_version/struct.VersionUpdater.html#method.with_features_always_increment_minor).

## Alternatives

None known.

**Comment by MarcoIeni** [comment]
closed by #1657
