### ISSUE TITLE
Could not release on artifactory

### ISSUE THREAD

**Issue by davidB** [MarcoIeni/release-plz#1668]
## Bug description
We used jfrog/artifactory (cloud) as registry for private crates.
We can `cargo fetch`  ... `cargo publish`. 

But when we try to use `release-plz` we got error to retrieve metadata

On github runner  (ubuntu-latest):

```txt
Caused by:
    0: timeout while publishing axum-extra-derive
    1: failed fetching sparse metadata
    2: error sending request for url (https://mycompany.jfrog.io/artifactory/api/cargo/mycompany-cargo-local/index/ax/i-/axum-extra-derive)
    3: client error (Connect)
    4: error:0A000460:SSL routines:ssl3_read_bytes:tlsv1 alert no application protocol:ssl/record/rec_layer_s3.c:907:SSL alert number 120
    5: error:0A000460:SSL routines:ssl3_read_bytes:tlsv1 alert no application protocol:ssl/record/rec_layer_s3.c:907:SSL alert number 120
```

On local (macos x86):

```txt
  2024-09-09T10:58:34.754858Z ERROR  can't determine if package is published

Caused by:
    0: timeout while publishing axum-extra-derive
    1: failed fetching sparse metadata
    2: error sending request for url (https://mycompany.jfrog.io/artifactory/api/cargo/mycompany-cargo-local/index/ax/i-/axum-extra-derive)
    3: client error (Connect)
    4: Fatal alert

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: std::backtrace::Backtrace::capture
   2: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   3: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll
   4: release_plz_core::cargo::is_published::{{closure}}
   5: release_plz_core::command::release::release_package_if_needed::{{closure}}
   6: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   7: release_plz::run::{{closure}}
   8: tokio::runtime::park::CachedParkThread::block_on
   9: release_plz::main
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: _main
  14: <unknown>
```

Timeout is not the root cause, because it failed immediately, the wrong error message/context is another topic.

I guess both errors are related because the request uses `native-tls` that imply a different behavior on mac & linux regarding SSL and HTTP 2.0

- Would you like to work on a fix? Y

I have a workaround, I can make a PR

- On my local fork I forced the use of HTTP 1.1 to retrieve metadata, it works on Mac but seems slow.
- As a more general proposal, I'm exploring http2 as currently but retry with HTTP 1.1 if there is an error during the request (slower for people like me, but no impact for crates.io and others)
- Can I open a PR to discuss the details?

## To Reproduce

1. setup a cargo registry sparce+index over HTTP 1.1 (not only http2), or use artifactory (commercial version)
2. try to release a crate on it

## Expected behavior

No error

## Environment

- OS: macos x86 and gihub runner
- release-plz version: 0.3.87
- registry: jfrog/artifactory cloud (sparce+index)

**Comment by MarcoIeni** [comment]
> Can I open a PR to discuss the details?


Sure!

**Comment by davidB** [comment]
Thanks for the release, I'll test on github runner with our jfrog to check if it also solve the ssl issue as expected
