### ISSUE TITLE
git_release_enable flag not working

### ISSUE THREAD

**Issue by dj8yfo** [MarcoIeni/release-plz#1677]
## Bug description

- Would you like to work on a fix? [y/n] - n

## To Reproduce

1. despite specifying flag https://github.com/near/cargo-near/blob/main/release-plz.toml#L15
2.  github release was created during merge of https://github.com/near/cargo-near/pull/214

## Expected behavior

Github release for `cargo-near-build` not created

## Screenshots
![image](https://github.com/user-attachments/assets/d779b2dd-e2d6-4597-9735-d095bcf4cb87)

## Environment

github action: https://github.com/near/cargo-near/blob/main/.github/workflows/release-plz.yml#L27

- OS: [e.g. Ubuntu 20.04]
- release-plz version: [e.g. 0.5 action in workflows]

**Comment by MarcoIeni** [comment]
I'll have a look, thanks for reporting.

I noticed you specify twice `git_release_enable = false` in your config, which doesn't make sense because the second one will override the first one with the same value

**Comment by MarcoIeni** [comment]
I couldn't reproduce your issue. I tested it in my repo at [this](https://github.com/MarcoIeni/rust-workspace-example/commit/a22163cdba39a546381bffb96a575f6de64ac0cf) commit.

I had a deeper look in your CI and it seems that the release was published by cargo-dist, not release-plz: https://github.com/near/cargo-near/blob/main/.github/workflows/release.yml

**Comment by dj8yfo** [comment]
@MarcoIeni sorry about the issue).
I should've properly looked myself prior to raising it

**Comment by MarcoIeni** [comment]
no worries, have a nice week :)
