### ISSUE TITLE
Commits to child crate is added to changelog of parent crate in workspace

### ISSUE THREAD

**Issue by Profiidev** [MarcoIeni/release-plz#1701]
## Bug description

When I have multiple crates in the same workspace and make a commit with changes only to a child crate then the commit is also added to the parent crate in the changelog and the version of the parent crate is bumped.

## Example
https://github.com/Profiidev/release-plz-test/pull/1

**Comment by MarcoIeni** [comment]
I also see "initial commit" which involved both crates I guess

**Comment by Profiidev** [comment]
The commit i mean is the 'subcrate edit' commit

**Comment by MarcoIeni** [comment]
oh, yes, you are right. PR welcome! Otherwise I can look into this around 28 September

**Comment by Profiidev** [comment]
I will try to look into the code and see if I can fix it
