### ISSUE TITLE
Create GitHub releases on `release`

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#171]
## Motivations

It would be nice to publish GitHub releases after creating the tag.
You can see an example of a GitHub release created by release-please [here](https://github.com/googleapis/release-please/releases/tag/v13.17.1).
Ideally, we should implement something like that.

## Problem

Usually, you want to add binaries and other artefacts to the release.
How does the user attaches these files if we create the GitHub release?
This makes me wonder if we should implement this feature or not.

## Solution

There should be an additional flag to the `release` command.
The functionality is disabled by default.

**Comment by yusefnapora** [comment]
Hey, I just discovered release-plz after fighting with release-please for a bit. It seems really cool so far, so thanks!

I'm interested in this issue, since my strategy with release-please was to run a "release binaries" workflow triggered on the GitHub actions `release` event. That works as long as you don't use the default `GITHUB_TOKEN` in the release-please action.

**Comment by MarcoIeni** [comment]
Hi Yusef, thanks!

> triggered on the GitHub actions release event.

So you can add binaries and file to a release after the release is created?

**Comment by yusefnapora** [comment]
Yes, exactly. I currently have a [release-binaries workflow](https://github.com/yusefnapora/w3name-rust-client/blob/main/.github/workflows/release-binaries.yml) that runs on the "release created" event. But that event only gets dispatched if you tell `release-please` to use a non-default github token.

**Comment by MarcoIeni** [comment]
Well, that's cool! We could add a flag to the `release-plz release` command to also generate a github release.

For example `release-plz release --gh-release`.

Do you think we can re-use the same github token we are already using in release-plz or we would have issues similar to release-please?

Anyway, if you want to work on this, a PR is welcome! :)

**Comment by MarcoIeni** [comment]
- [ ] Gitea also has releases. Before closing this issue, I want to add support for gitea releases, too.

**Comment by MarcoIeni** [comment]
You can now create github releases with:
`release-plz release --git-token ${GITHUB_TOKEN} --git-release`.

## GitHub action

The GitHub action creates releases by default 👍 
You can turn off this feature by changing the `git_release` flag.
