### ISSUE TITLE
Configure Branch Prefix for release-pr

### ISSUE THREAD

**Issue by rajeshn76** [MarcoIeni/release-plz#1728]
## Motivations

While creating a release PR, release-plz creates a new branch to commit the changes prior to the Pull Request. This feature uses a constant branch prefix, hard-coded to "release-plz-". In some cases, this naming convention can be too restrictive, if say, there are branch rules set that disallow branch names that do no follow certain naming standards set within an organization.

In order to circumvent this problem, users need a way to set their own branch prefixes that adhere to the branch targeting criteria set within Github rulesets.

- Would you like to implement this feature? yes

## Solution

Externalize the BRANCH_PREFIX value to be an environment variable, so that the value can be overridden at run time, instead of being hard-coded as a constant. If the value is not set, then default the branch prefix to its current value of "release-plz-".

## Additional context

By allowing to change the prefix, the user would be inheriting some risk, say, in the case of choosing a bad prefix that overlaps with other non-release-plz managed branches, but that is an acceptable risk.

**Comment by rajeshn76** [comment]
Pls review the PR # https://github.com/MarcoIeni/release-plz/pull/1737

**Comment by MarcoIeni** [comment]
closed by https://github.com/MarcoIeni/release-plz/pull/1737
