### ISSUE TITLE
Feedback on attempts to use release-plz on cargo-show-asm

### ISSUE THREAD

**Issue by pacak** [MarcoIeni/release-plz#1738]
Disclaimer: it might not represent current behavior or it might represent the default behavior and it is possible to configure it differently right now.

I'm going to talk about this pull request: https://github.com/pacak/cargo-show-asm/pull/260

- Title `chore: release v0.2.31`
  I don't use conventional commits, "chore" is 100% noise. Release should be capitalized.
- `🤖 New release`
  Emoji - junk, "new release" is redundant, merge request title already said so.
- `cargo-show-asm: 0.2.30 -> 0.2.31`
  As far as users are concerned there's only one crate in this repo - crate name is redundant, old version doesn't matter, new version was listed in the title. 
- All the changelog contents
  Again - not using conventional commits. I write commits for myself, I write entries in `Changelog.md` for users, they serve different purposes, you can't generate both of them from the same source. Example - should users care about "Fixed: Change branch to master"?
- footer "This PR was generated with release-plz".
  Noise. I don't care, users don't care.

What I want is to see a simple title, my changelog entry and nothing else.

**Comment by MarcoIeni** [comment]
Hi! Thanks for the detailed feedback, very appreciated! 

You're right, what you described is the default behavior and can't be changed. 

I opened https://github.com/MarcoIeni/release-plz/issues/1740 and https://github.com/MarcoIeni/release-plz/issues/1741

They should solve your issues because they allow to customize the pr name and body as you want with tera templates 👍

**Comment by marcoieni** [comment]
Hey, you can now customize the pr body as you prefer. [Here's](https://release-plz.dev/docs/config#the-pr_body-field) the default configuration 👍

You can also configure the [pr name](https://release-plz.dev/docs/config#the-pr_name-field) and you can disable [changelogs](https://release-plz.dev/docs/config#the-changelog_update-field).

I think all your points are now addressed 👍
