### ISSUE TITLE
Add configuration field to customize release PR name

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1740]
## Motivations

Not everyone likes the format `chore: release v0.2.31`.

## Solution

Add a [config](https://github.com/MarcoIeni/release-plz/blob/46f6489613eeb5a68d01c7845f0622f722c80d6a/website/docs/config.md#L52) field called `pr_name`. Similar to the `git_tag_name` field, the `pr_name` field should be a tera template.

The field `{{ version }}` should be available

## Additional context

Requested in https://github.com/MarcoIeni/release-plz/issues/1738

**Comment by JustBeYou** [comment]
Hi @MarcoIeni, I was looking to get into some OSS development in the Rust space and your project caught my attention. Is it ok if I'd try my luck starting with a contribution for this issue?

**Comment by MarcoIeni** [comment]
Sure, this is a good issue to get started I think :)
I assigned it to you, let me know if you have any questions 👍

**Comment by JustBeYou** [comment]
I'm not really sure how should we handle things when multiple packages are released, I see in the current behavior, the package name and the version are not shown when multiple packages with different versions are released.

Should we allow an array of values for the package/versions? I think it could work, but also bring some clutter if improperly used.

What do you think?

**Comment by MarcoIeni** [comment]
> Should we allow an array of values for the package/versions in the template?

For now let's not do this. Maybe in the future in another PR 👍

If multiple versions are present, you can set `{{ version }}` to be empty string
