### ISSUE TITLE
Add configuration field to customize the pr body

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1741]
## Motivations

Not everyone likes the default release PR body.

## Solution

Add a [config](https://github.com/MarcoIeni/release-plz/blob/46f6489613eeb5a68d01c7845f0622f722c80d6a/website/docs/config.md#L52) field called `pr_body`. Similar to the `git_tag_name` field, the `pr_body` field should be a tera template.

Edit [this](https://github.com/MarcoIeni/release-plz/blob/46f6489613eeb5a68d01c7845f0622f722c80d6a/crates/release_plz_core/src/pr.rs#L83) function.

You need to add to the template a context with the array `{{ releases }}` (Similar to how `{{ remote.contributors }}` works in [git_release_body](https://github.com/MarcoIeni/release-plz/blob/69ad93ecae7ab480469168aa9b4f29182d48ff80/website/docs/config.md#L224)).

Those two should be two objects so that people can format them how they want.

- array `releases` (to find all these data check in [changes](https://github.com/MarcoIeni/release-plz/blob/0cf73c99ef6908f579d96978136e455432a7a3df/crates/release_plz_core/src/command/update.rs#L77) and [updates_summary](https://github.com/MarcoIeni/release-plz/blob/0cf73c99ef6908f579d96978136e455432a7a3df/crates/release_plz_core/src/command/update.rs#L57) functions:
  - `package` (e.g. `my_package_name`)
  - `title` (e.g. `[0.3.96](https://github.com/MarcoIeni/release-plz/compare/release-plz-v0.3.95...release-plz-v0.3.96) - 2024-10-05`)
  - `changelog` (e.g. `### Added ...`)
  - `previous_version` (e.g. `1.2.3`)
  - `next_version` (e.g. `1.2.4`)

## Additional context

asked in https://github.com/MarcoIeni/release-plz/issues/1738

**Comment by JustBeYou** [comment]
Hi, @MarcoIeni, I going to give a shot to this too, it would be great if you could assign it to me.

**Comment by MarcoIeni** [comment]
thanks, done! :)

**Comment by MarcoIeni** [comment]
I opened https://github.com/MarcoIeni/release-plz/issues/1788 which is related to this issue.
Mainly to improve the docs 👍
