### ISSUE TITLE
release-plz init: check if the mandatory fields of `Cargo.toml` are present

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1762]
## Motivations

Many people forget to add `license` and `description` to their Cargo.toml.

## Solution

Use the cargo metadata library to check if these fields are present in all non public packages. You can use [this](https://github.com/MarcoIeni/release-plz/blob/c664c887c510766c1964260bb4b633e7ddace625/crates/release_plz_core/src/project.rs#L91) function

If something is missing, fail and report the error.

**Comment by KekmaTime** [comment]
@MarcoIeni i would like to work on this issue 😃

**Comment by MarcoIeni** [comment]
Go for it!!

**Comment by KekmaTime** [comment]
@MarcoIeni I've made the implementation, how do i integrate it with the main code? I'm kinda stuck tbh

**Comment by MarcoIeni** [comment]
I didn't get what you mean.
Can't you open the pr? 🤔

**Comment by MarcoIeni** [comment]
Did you wrote the implementation in a new project and you want to move it to release-plz?
