### ISSUE TITLE
Add `remote.pr_number` to `remote` context of commits in changelog

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1767]
## Motivations

Needed for ratatui!

## Solution

Fill `pr_number` of `RemoteContributor` struct.
Do it here: https://github.com/MarcoIeni/release-plz/blob/51416d4e9e69cfcdd3a12df069bace6d6f839b8f/crates/release_plz_core/src/changelog_filler.rs#L46

**Comment by KekmaTime** [comment]
@MarcoIeni i can work on this issue if you can assign me this. Also is the ratatui issue you have mentioned a reference to this issue?

**Comment by MarcoIeni** [comment]
> i can work on this issue if you can assign me this.

Done, thanks!

> Also is the ratatui issue you have mentioned a reference to this issue?

Yes 👍

**Comment by KekmaTime** [comment]
I'm not gonna lie the gitea part was a bit tricky since i have'nt used gitea till now
