### ISSUE TITLE
Error: `can't find git client`

### ISSUE THREAD

**Issue by Leandros** [MarcoIeni/release-plz#1779]
## Bug description

I am trying to run `release-plz release-pr` on my [Ferrunix](https://github.com/Leandros/ferrunix) code base.

## To Reproduce

1. Clone [ferrunix](https://github.com/Leandros/ferrunix)
2. Checkout revision [df4dd5fac707600ecbb5b6457a6634fcf403a65b](https://github.com/Leandros/ferrunix/commit/df4dd5fac707600ecbb5b6457a6634fcf403a65b)
3. Run `release-plz release-pr`

## Expected behavior

A release PR is created.

## Screenshots

See logs below.

## Environment

- OS: macOS Sonoma 14.5 (`Darwin Arvids-MBP.fritz.box 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64`)
- release-plz version: 0.3.102
- git version: version 2.38.1
- `which git`: ﻿/opt/homebrew/bin/git
- `where git`: 
```
/opt/homebrew/bin/git
/usr/bin/git
```

## Additional context

Full log, with `TRACE`: [log.txt](https://github.com/user-attachments/files/17406239/log.txt)

**Comment by MarcoIeni** [comment]
You need to pass the `--git-token` argument.
If you have the gh cli installed you can do 

```
export GITHUB_TOKEN=$(gh auth token)
release-plz release-pr --git-token ${GITHUB_TOKEN}
```

The error message is really bad, I'll try to fix it 👍

**Comment by MarcoIeni** [comment]
Regarding [this](https://github.com/Leandros/ferrunix/commit/d65af9762ee632c35d906f169fc4ddb2c9b289e7)

Why did you use

```
on:
  push:
    tags:
      - "*"
```

That's not how release-plz is meant to work.

**Comment by MarcoIeni** [comment]
That docs explain how to run YOUR actions after release-plz runs.
Eg you want to publish the binary.

Copy paste the entire action from the quickstart guide and it should be fine 👍
