### ISSUE TITLE
failed to update packages: Cargo.lock

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#1791]
## Bug description

Hello, since pushing some new crates commits I've been getting the following error in CI, I've also tried running release-plz locally and also get the error, however I can't seem to fix it because I don't get a new `Cargo.lock` running `cargo update` or `release-plz update` so I don't know how to fix it.

https://github.com/librasn/rasn/actions/runs/11419906730/job/31775006033

- Would you like to work on a fix? n

## To Reproduce

1. `git clone` https://github.com/librasn/rasn
2. `release-plz update`

## Expected behavior

release-plz provides the diff or works.

**Comment by MarcoIeni** [comment]
I'm busy for now. Maybe I can have a look next weekend

**Comment by Nicceboy** [comment]
I tried to go back in versions with `cargo install` to see whether this was potentially introduced recently, but it seems like that some dependencies are not defined strictly enough and installation can fail for older versions:

```cmd
cargo install --version 0.3.91 release-plz
```
would produce

```cmd
   Compiling release_plz_core v0.26.2
error[E0063]: missing fields `output` and `render_always` in initializer of `ChangelogConfig`
   --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/release_plz_core-0.26.2/src/changelog.rs:375:5
    |
375 |     ChangelogConfig {
    |     ^^^^^^^^^^^^^^^ missing `output` and `render_always`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `release_plz_core` (lib) due to 1 previous error
error: failed to compile `release-plz v0.3.91`, intermediate artifacts can be found at `/tmp/cargobuilds`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by Nicceboy** [comment]
Commit 99c4f6f9fb78316efd1e387945c1dc971d544966 seems to introduce this issue at least on my machine.

**Comment by MarcoIeni** [comment]
For the installation, you could try adding the --locked flag:

`cargo install --version 0.3.91 release-plz --locked`



> Commit [99c4f6f](https://github.com/MarcoIeni/release-plz/commit/99c4f6f9fb78316efd1e387945c1dc971d544966) seems to introduce this issue at least on my machine.

That's very helpful, thanks!

Can you create a small repo to reproduce the error?

**Comment by Nicceboy** [comment]
> For the installation, you could try adding the --locked flag:
> 
> `cargo install --version 0.3.91 release-plz --locked`
> 
> > Commit [99c4f6f](https://github.com/MarcoIeni/release-plz/commit/99c4f6f9fb78316efd1e387945c1dc971d544966) seems to introduce this issue at least on my machine.
> 
> That's very helpful, thanks!
> 
> Can you create a small repo to reproduce the error or is it too complex?

Ah that helps. So ` cargo install --version 0.3.94 release-plz --locked` will also introduce the issue (includes the above commit) and `cargo install --version 0.3.93 release-plz --locked` works. I made a branch with smaller set of changes in my fork of `rasn`, which introduces the issue: https://github.com/Nicceboy/rasn/tree/release-plz-sample However, I am afraid I cannot spend more time for this right now.

**Comment by MarcoIeni** [comment]
I can't reproduce this issue anymore unfortunately/fortunately :/

**Comment by MarcoIeni** [comment]
I merged #1803 
I'll release the new version of the gh action.
If you still experience the same error, please open a new issue or re-open this one 👍

**Comment by Nicceboy** [comment]
Thank you! It is very odd, I could not reproduce this problem either anymore, with identical process as previously.

**Comment by MarcoIeni** [comment]
github action released 👍

**Comment by XAMPPRocky** [comment]
> I can't reproduce this issue anymore unfortunately/fortunately :/

If I had a theory, I'd reckon it requires an unreleased crate to be replicated, because that is the only change between me filing and then you attempting.
