### ISSUE TITLE
release-plz incorrectly tagging a commit from squashed PR

### ISSUE THREAD

**Issue by scouten-adobe** [MarcoIeni/release-plz#1799]
## Bug description

As of recently (not sure, but guessing #1761 or #1775), release-plz has started tagging the commit from the PR that has been squashed _rather_ than the PR's commit to `main`.

This results in an undesirable timeline where the tags are spurs off of the mainline.

See most recent release from https://github.com/scouten-adobe/rp-sandbox for an example of this effect.

- Would you like to work on a fix? [y/n]

_Possibly, though I will be attending a conference and only sporadically available for the next week._

## To Reproduce

Using the repo https://github.com/scouten-adobe/rp-sandbox, I was able to reproduce this with the following:

1. Make a trivial change; just enough to trigger a release. (See https://github.com/scouten-adobe/rp-sandbox/commit/8acc130e87bd314daa3d8b26ed115eb1557540fc.)
2. Wait for the release PR to be created. (See https://github.com/scouten-adobe/rp-sandbox/pull/21.)
3. Merge that PR.
4. Wait for the release to occur.
5. Check the commit history.

## Expected behavior

The commit to `main` is tagged with the release. (In this case, that would be https://github.com/scouten-adobe/rp-sandbox/commit/e5e3e1bd3ac9f72078d94e9bd9d3d6e118cc0e72.)

## Observed/unwanted behavior

The commit from the PR that was squashed is tagged with the release. (In this case, that was https://github.com/scouten-adobe/rp-sandbox/commit/cb4858a0e7bcf462165f02463d73b541e802fa69, which – because I delete PR branches automatically after merging – comes with the warning: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.")

**Comment by scouten-adobe** [comment]
For anyone else affected by this, freezing the GitHub action at `release-plz-action@v0.5.76` (instead of the more generic `v0.5` reference) seems to avoid this problem.

**Comment by MarcoIeni** [comment]
Ooops, sorry!

I tried to fix this in https://github.com/MarcoIeni/release-plz/pull/1801 but I need to test it before merging.

**Comment by scouten-adobe** [comment]
Thank you for quick fix! I'll watch for the new release.

**Comment by MarcoIeni** [comment]
released, let me know if it fixes this issue for you!

**Comment by scouten-adobe** [comment]
@MarcoIeni confirmed fixed in `release-plz-action@v0.5.81`. Thank you! 🙏🙏🙏

**Comment by MarcoIeni** [comment]
No worries, and sorry again for the trouble. 👍
