### ISSUE TITLE
Edit release-plz PR instead of closing it

### ISSUE THREAD

**Issue by nahsi** [MarcoIeni/release-plz#280]
## Motivations

It would be nice if instead of closing release-plz PR and opening new one release-plz were able to change existing PR similar to how it is done in [release-please from google](https://github.com/google-github-actions/release-please-action)

- Would you like to implement this feature? [y/n] n

**Comment by MarcoIeni** [comment]
I agree with you. It would be nice!
However we need to think about the strategy. 

What does release-please do? Does it force push?
If we force push there is the risk of overriding user commits. For example, if a dependabot pr is merged after the user edited the release-plz pr.

**Comment by MarcoIeni** [comment]
> What does release-please do? Does it force push?

Yes, see https://github.com/starship/starship/pull/4485 for example.

> In this scenario what should we do? If we force-push we lose the developer edit in the changelog

Maybe we can check the commit history of the PR. If there's only one author (the release-plz bot), we force-push. Otherwise, we close the PR and we create a new one.

**Comment by MarcoIeni** [comment]
- [x] github: done in https://github.com/MarcoIeni/release-plz/pull/470
- [ ] gitea: TODO

**Comment by MarcoIeni** [comment]
bug: https://github.com/MarcoIeni/release-plz/pull/452#issuecomment-1406151688
