### ISSUE TITLE
Integrate with `cargo-semver-checks`

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#373]
## Motivations

[`cargo-semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) is a tool that checks whether the new version breaks the public API of the crate.
It would be great if release-plz could show in the PR description if something is breaking.
Also update the version accordingly (only for libraries).

Only run the check on library crates, not binaries. 

## Solution

Blocked by https://github.com/obi1kenobi/cargo-semver-checks/issues/67

## Additional context

I haven't tried this tool yet. Other ideas are welcome!

**Comment by obi1kenobi** [comment]
Marco wrote the PR that closed that issue :)
https://github.com/obi1kenobi/cargo-semver-checks/pull/314

We're making progress on it! I'm just stretched quite thin across a few too
many concurrent issues at the moment.

**Comment by MarcoIeni** [comment]
Hey XAMPPRocky, thanks for the heads up! As Pedrag said, I am aware of that.
However, the library as some limitations at the moment. See https://github.com/obi1kenobi/cargo-semver-checks/issues/396
For sure when the library is ready, I will use that one instead of the binary!

> I'm just stretched quite thin across a few too
many concurrent issues at the moment.

Pedrag, don't stretch yourself too much, you are already doing a wonderful job ❤️

**Comment by MarcoIeni** [comment]
It was surprisingly easy to integrate cargo-semver-checks by running the binary.
The separation between stdout and stderr helped a lot!
Here is a test: https://github.com/MarcoIeni/release-plz/pull/569 (feedback on the report format is welcome).
I run cargo-semver-checks only if it's installed, and there's no way to disable the check at the moment. Not sure if it's worth adding a cli flag. I assume you almost always want to run this check. We'll see.

In the github action I install both the `cargo-semver-checks` and `release-plz` binaries by downloading them from the GitHub releases.

The next release of release-plz will include this integration! :D

**Comment by obi1kenobi** [comment]
This is awesome! 🎉

> there's no way to disable the check at the moment

As hard as we try in `cargo-semver-checks`, from time to time false-positives do sneak in. It might be good to have the equivalent of `cargo publish --allow-dirty` to allow publishing even though `cargo-semver-checks` thinks the change shouldn't be allowed.

**Comment by MarcoIeni** [comment]
You can still merge the pr, even if there is a semver incompatibility.
Release-plz in this case bumps the major version, so it's safe to release 👍
In case there's a false positive, users can change the version proposed by release-plz.

If you find the docs confusing or you want to see a demo of release-plz, just tell me :)

**Comment by MarcoIeni** [comment]
An example of a PR with comments:
<img width="1149" alt="chore__release_by_release-plz_bot__·_Pull_Request__570_·_MarcoIeni_release-plz" src="https://user-images.githubusercontent.com/11428655/221430686-b75f50c4-8eff-4340-a312-f1d4c24b9bad.png">

**Comment by obi1kenobi** [comment]
That looks great, I love it! 🎉
