### ISSUE TITLE
Create Gitea releases on release

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#418]
## Motivations

Similar to #171, but for Gitea.

**Comment by gautamprikshit1** [comment]
Is Gitea not supported by Octocrab?

**Comment by MarcoIeni** [comment]
No, they don't support it. 
For gitea we use a plain http client.
see https://github.com/MarcoIeni/release-plz/blob/0ef8f3fe78bdbeffe496ef29a663671bbcafe9e5/crates/release_plz_core/src/gitea_client.rs#L29
