### ISSUE TITLE
Warn on circular dependency

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#507]
## Motivations

You can't publish packages when there are circular dependencies. Example [here](https://github.com/MarcoIeni/release-plz/pull/452#issuecomment-1409803442).

## Solution

In these cases, release-plz shouldn't try to publish one of the two packages. Instead, it should give an error mentioning the two packages.

**Comment by brainstorm** [comment]
Here's another side-effect on publishing **some** of the crates of a workspace with circular deps:

<img width="966" alt="Screenshot 2023-02-07 at 5 04 45 pm" src="https://user-images.githubusercontent.com/175587/217161859-581ad717-0c48-42c7-8d76-056c6ba00072.png">

I manually yanked that `htsget-config` version in hopes that `release-plz` would pick it up and perhaps go ahead with release 0.1.2 with the rest of the crates on a next PR/commit, but instead [`release-plz` detects the different local vs crates.io versions](https://github.com/umccr/htsget-rs/actions/runs/4110844870/jobs/7094043464)  and decides not to create a new release PR:

<img width="988" alt="Screenshot 2023-02-07 at 5 06 09 pm" src="https://user-images.githubusercontent.com/175587/217162134-91efc70a-6a86-4bff-ac15-618f8498d2d7.png">

I don't necessarily expect `release-plz` to solve this on its own (maybe it is reasonable it does? I don't know), but I'm just wondering how to solve it now without introducing other issues on subsequent releases? Current `main` status:

```
(base) rvalls@m1 htsget-rs % find . -iname "Cargo.toml" | xargs grep ^version
./htsget-search/Cargo.toml:version = "0.1.1"
./htsget-lambda/Cargo.toml:version = "0.1.1"
./htsget-test/Cargo.toml:version = "0.1.1"
./htsget-http/Cargo.toml:version = "0.1.1"
./htsget-actix/Cargo.toml:version = "0.1.1"
./htsget-config/Cargo.toml:version = "0.1.1"
```

Options I've been thinking (as a user) without looking through release-plz logic (yet):

1. Manually downgrade local versions to 0.1.0?
2. Manually bump up everything to 0.1.2?
3. There's no point 3 ;P

/cc @mmalenic

**Comment by MarcoIeni** [comment]
My understanding is that `release-plz release-pr` thinks that the latest version of htsget-config is 0.1.0, even if there's a 0.1.1 yanked. (`htsget-config: the local package has already a different version with respect to the registry package, so release-plz will not update it`).

Then `release-plz release` detects that the version is already published, so it does nothing.

The error is in `release-plz release-pr`, which should detect also yanked versions.

Isn't [this](https://github.com/umccr/htsget-rs/actions/runs/4118501133/jobs/7111087479) the github action job after you merged option 1?
1. it detects that next version is 0.1.1.
2. it opens https://github.com/umccr/htsget-rs/pull/154
3. You merge this and `release-plz release-pr` still complaints: `the local package has already a different version with respect to the registry package, so release-plz will not update it`. This is because `release-plz release-pr` thinks that the latest version is 0.1.1.

I opened https://github.com/MarcoIeni/release-plz/issues/524

Thanks for reporting this!

For now, I would suggest going with option 2. I.e. manually bumping everything to 0.1.2 :(
`release-plz release-pr` won't generate a new release pr, but once you release with `release-plz release`, everything will go back to normal.

You can use `cargo set-version` from the `cargo-edit` crate to easily set the versions.

**Comment by brainstorm** [comment]
Manually bumping to `0.1.2` didn't result in a clean cut release either, unfortunately: https://github.com/umccr/htsget-rs/actions/runs/4218947590/jobs/7323857467#step:3:387

/cc @mmalenic

**Comment by MarcoIeni** [comment]
It's not an issue with release-plz.
I was able to reproduce the same issue by running `cd htsget-search && cargo publish --dry-run`.

Error message:
```
Caused by:
  feature `s3-storage` includes `htsget-test/s3-storage`, but `htsget-test` is not a dependency
```

which refers to [this](https://github.com/umccr/htsget-rs/blob/0f64f48b9381de29309cfb6c398969b178d7187f/htsget-search/Cargo.toml#L14) line.

**Comment by brainstorm** [comment]
Thanks and sorry for the noise Marco, we need to break up htsget-test so that it doesn't cause those problems in the future.
