### ISSUE TITLE
Add shell completion

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#59]
## Motivations

It's nice to hit TAB for autocomplete!

## Solution

Use `clap_complete`. 
You can find an example [here](https://github.com/alexheretic/ab-av1/blob/main/src/command/print_completions.rs)

**Comment by Rqnsom** [comment]
Can I try this one?

**Comment by MarcoIeni** [comment]
yes, please! :)

**Comment by Rqnsom** [comment]
Thanks!
Here is my [PR](https://github.com/MarcoIeni/release-plz/pull/177). Is it normal to link it from here once it is in progress?

**Comment by MarcoIeni** [comment]
Yes, thanks! You can also refer this issue from the PR :)
