### ISSUE TITLE
Support projects not published in cargo registries

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#590]
## Motivations

Some people don't want to publish their project on crates.io or other cargo registries.
However, they still want to bump their versions and create git tags and git releases.

Currently, release-plz ignores packages with the flag `publish=false` in their Cargo.toml

## Solution

I need to think about it. Maybe a configuration flag in the config file. Something like `git-only=true` or `cargo-registry=false`.

## Additional context

- relevant issue: https://github.com/crate-ci/cargo-release/issues/583

**Comment by MarcoIeni** [comment]
We could use the package.my_package.releaese.enable as a config parameter.
Possible values: yes, no, auto.

Auto is by default. The project is published if the publish flag of the cargo.toml is true.
Instead, if the publish flag is false. The package at the moment is totally skipped.

With true, you enable git only releases

False it makes no sense, because it's the same of the publish flag to false, right?

**Comment by flying-sheep** [comment]
To enable my use case mentioned in #711, there should be the following configurations:

1. don’t do any release or tag (already supported by specifying `command: release-pr`)
2. create tag+GH release, publish to crate registry if `publish = true` in Cargo.toml is set
3. create tag+GH release, don’t publish to crate registry (when people want to use e.g. `cargo-publish` in a separate workflow with `on: release`) ← my use case
4. ~~GH release, tag, and publish to crate registry no matter what `Cargo.toml` says~~ (I think this makes no sense)

I think a config option called `release` is a bit misleading for enabling use cases 2&3, as a GitHub release still happens. Maybe call it `publish` or `upload` or sth. with `crate`?

**Comment by MarcoIeni** [comment]
I think `publish = false/true` makes sense 👍 
We already have `publish_dry_run` and `publish_no_verify` that refer to `cargo publish`.

I think we can have two separate issues here:

- [ ] add `publish` flag to the configuration file that enables/disables `cargo publish` (defaults to true). This will enable your use case 👍 
- [ ] before downloading the crate from the registry, check if the tag exists locally and use that tag for comparison. (more complex, but still feasible) (low priority)

If we implement both these features, we can enable this use case. What do you think? If you agree I will close this issue and open these new ones. The `publish` flag can be added easily 👍 If you want to do it, it's a nice good first issue :) You can have a look at how the configuration fields `publish_no_verify` and `publish_allow_dirty` work.

**Comment by flying-sheep** [comment]
Sounds great! I’ll take a look into implementing it

**Comment by MarcoIeni** [comment]
Created the first issue: https://github.com/MarcoIeni/release-plz/issues/719

**Comment by MarcoIeni** [comment]
Regarding the support for packages not published to a cargo registry, I'm not sure I want to support this use case because it brings complexity into the release-plz configuration file and the codebase itself.

For example, release-plz should start considering the packages with `publish = false` configuration of the Cargo.toml (not the one in release-plz.toml) if we want to release them with git tags only. So in this case we need a `git_tag = true/false` config option, too.
However, now we assume that every package releases a git tag. 

Anyway, the best approach to do this at the moment seems to introduce a `git_only` config option, where release-plz uses the git tags to determine what's the latest version of the package. So we might need the logic to determine the latest tag.


I will close this for now because this issue introduces more complexity with respect to the value it brings. 

If many people wants this in release-plz, MAYBE I might reconsider my opinion.

**Comment by MarcoIeni** [comment]
Reopened this issue here: https://github.com/MarcoIeni/release-plz/issues/1144
