### ISSUE TITLE
release PR content / title configurability

### ISSUE THREAD

**Issue by sassman** [MarcoIeni/release-plz#592]
## Suggestion

- It would be very handy if the release PR would contain 
the excerpt of the corresponding change log directly in the PR Description.
- It would also be very handy to see the version number directly in the commit and hence in the PR Headline

Dependabot has a similar behavior, only there the so-called "Release Notes" are a collapsable area.

This screenshot should illustrate it:

![image](https://user-images.githubusercontent.com/329682/223880819-abd028c3-4228-4471-ab8b-b6d38e8effee.png)

- So we see the PR Title is `chore: release 0.1.0-alpha.10` that contains the version number
- The Body contains additionally 
```markdown
## Changelog

### [0.1.0-alpha.10](https://github.com/curlz-rs/curlz/compare/v0.1.0-alpha.9...v0.1.0-alpha.10) - 2023-03-08

### Added
- *(cli)* implement `-u | --user` request cli argument (#7) (#46)
- *(template)* implement the basic auth template function (#7) (#33)
- *(template)* support environment variables from process / shell (#30) (#31)

### Other
- migrate to clap v4 (#54)
- *(deps)* bump pest from 2.5.5 to 2.5.6 (#51)
- release 0.1.0-alpha.9 (#45)
- release (#43)
- release (#39)
- release 0.1.0-alpha.6 (#34)
- release `0.1.0-alpha.5` (#29)
```

You find the screenshot related [example here](https://github.com/curlz-rs/curlz/pull/53)

**Comment by MarcoIeni** [comment]
> It would be very handy if the release PR would contain
the excerpt of the corresponding change log directly in the PR Description.

I didn't implement this because I find it noisy. The changelog is already in the "Files" tab of the PR.
However, release-please shows the changelog in the PR body as well. So if you find it useful, let's do it :)

> Dependabot has a similar behavior, only there the so-called "Release Notes" are a collapsable area.

Judging on your example pr you don't want the changelog to be collapsable, right?

**Comment by sassman** [comment]
You might me right it will become noisy pretty quickly.

I would not mind having it also behind a collapsible area.

What might be also an option is to have a feature toggle on the GitHub action that one can use to opt into the changelog excerpt on the release PR or not. 

I would suspect that content on the PR is very likely matter of taste and hence flexibility is long term inevitable. But me personally I'm very much fine with either ways. And i fear as you that it will become noisy too.

**Comment by MarcoIeni** [comment]
let's start by having the changelog behind a collapsible area.
If you or another user realize they would prefer not having the collapsible area (i.e. they prefer seeing the changelog in the pr body), we can add a configuration option to change this behavior :)

**Comment by MarcoIeni** [comment]
the pr title change is already deployed in the latest release.

I implemented the changelog report in https://github.com/MarcoIeni/release-plz/pull/598 and it will be available in the next release :)

**Comment by sassman** [comment]
Thank you so much!
