### ISSUE TITLE
Add ability to have a single changelog

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#637]
Requested [here](https://github.com/near/borsh-rs/pull/133#issuecomment-1480271704).
If a package inherits the workspace version, it doesn't make sense to update all the changelogs of all the packages.
Instead, update the changelog at the workspace level.

**Comment by MarcoIeni** [comment]
Actually this should be disabled by default probably. Every crate has different changes.
You could enable this via a config parameter

**Comment by MarcoIeni** [comment]
Actually this should be disabled by default probably. Every crate has different changes.
You could enable this via a config parameter

**Comment by MarcoIeni** [comment]
I thought about this. I don't think that mixing changelogs from different crates is a good idea because the result can be confusing.
The scenario I imagine is that there's one crate that is the most important, and you only care about the changes in that crate.

In this scenario, we could allow to set a `changelog_path` for this package. You could set the top directory of the project.
Then, one could disable the changelog generation of every other crate.

- [ ] document this configuration example in the website

**Comment by frol** [comment]
@MarcoIeni Sounds fair to me 👍

**Comment by MarcoIeni** [comment]
Thanks for the feedback Vlad, it means a lot!

I developed the feature in https://github.com/MarcoIeni/release-plz/pull/653

I will probably release the new version of release-plz and the github action tomorrow.
If you want, you can already test it with `release-plz update` by running cargo install against the git repo.

This is the [configuration](https://marcoieni.github.io/release-plz/config.html) required in `release-plz.toml`:

```toml
[workspace]
update_changelog = false

[package.your_special_package]
update_changelog = true
changelog_path = "./CHANGELOG.md"
```

**Comment by MarcoIeni** [comment]
I tested this release [here](https://github.com/MarcoIeni/rust-workspace-example/pull/143/files) and the workspace changelog is not created on the pr (it's created if I run `release-plz update` locally. I will investigate further.

**Comment by MarcoIeni** [comment]
I fixed the release-pr issue in https://github.com/MarcoIeni/release-plz/pull/669
The latest version of release-plz supports having a single changelog 🥳 
You can find the docs [here](https://marcoieni.github.io/release-plz/config.html) and [here](https://marcoieni.github.io/release-plz/extra/single-changelog.html).

FYI I also opened https://github.com/MarcoIeni/release-plz/issues/671
