### ISSUE TITLE
add ability to mark Gitea/GitHub release as draft

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#676]
## Motivations

This feature is useful if you want to update other artifacts to the release later and you want to publish the release after the update was successful. Also if you want to review the release and publish it manually afterwards.

## Solution

The config field already exists:
https://github.com/MarcoIeni/release-plz/blob/88894d4c611e33bf158485978b10f853901daacb/crates/release_plz/src/config.rs#L314
but it's not used. Use it here:
https://github.com/MarcoIeni/release-plz/blob/88894d4c611e33bf158485978b10f853901daacb/crates/release_plz_core/src/git/backend.rs#L181

The GitHub api call is documented [here](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release). As you can see you need to add a `draft` field in the body. This change should also work for [Gitea](https://codeberg.org/api/swagger#/repository/repoCreateRelease). 👍 

- [ ] also document this field in the [docs](https://github.com/MarcoIeni/release-plz/blob/88894d4c611e33bf158485978b10f853901daacb/website/docs/config.md#L42). Specify that GitLab doesn't [support](https://docs.gitlab.com/ee/api/releases/#create-a-release) it

**Comment by jdidion** [comment]
+1

This is essential if you want to use in conjunction with [cargo-dist](https://opensource.axo.dev/cargo-dist/) for adding binaries to releases and publishing afterwards.

**Comment by MarcoIeni** [comment]
Since it's a really easy issue, I hoped somebody else could pick this. If that's not the case, I'll try to implement this soon :)

**Comment by MarcoIeni** [comment]
Hey John, I have implemented this feature, and I will release the new release-plz version now.
If you manage to use release-plz with cargo-dist can you link me the repository?
I would like to document how the two can work together.
Also, let me know if you are interested in documenting your approach in https://release-plz.ieni.dev/docs/extra :)

**Comment by jdidion** [comment]
Thank you!
