### ISSUE TITLE
Configuration: add ability to create releases as prerelease

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#678]
In the config file:

```toml
[[package]]
name = "my_pkg"
# If set to auto, will mark the release as not ready for production
# in case there is a semver pre-release in the tag e.g. v1.0.0-rc1
# If set to prod, will mark the release as ready for production. (default).
# If set to pre, will mark the release as not ready for production.
git_release_type = "auto"
```

we already read this field from the config, but we don't use it:
https://github.com/MarcoIeni/release-plz/blob/06418c1d5766b3f139a754f43d94c792bb4cbd5d/crates/release_plz/src/config.rs#L314

You can take inspiration from https://github.com/MarcoIeni/release-plz/pull/986

**Comment by ybaldus** [comment]
Hi,

I would like to work on this issue. I looked through #986 and did something similiar for github. From my understanding of the API this is only possible for github, is that correct? How do you usually test those things? I'm a newcomer and also new to Rust and would like to contribute more often.

**Comment by MarcoIeni** [comment]
Hi! If gitea and gitlab don't have pre-releases, we can make this feature github only. Let's make it explicit in the doc 👍

Usually I test these things manually.
While for gitea I write integration tests since it's open source and I run it as a docker container together with the test suite 👍

**Comment by MarcoIeni** [comment]
Pr welcome! Release-plz is rust beginner-friendly, so no worries if the pr is not perfect

**Comment by ybaldus** [comment]
From my understanding github and gitea API is the same. 
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
https://docs.gitea.com/api/1.20/#tag/repository/operation/repoCreateRelease

For gitlab I couldn't find anything similar, same goes for the draft release:
https://docs.gitlab.com/ee/api/releases/#create-a-release

I will test my code now and create an integration test. Could you guide me to the right place within the documentation?

**Comment by MarcoIeni** [comment]
Sounds good! For the docs, you can add the new option here: https://release-plz.ieni.dev/docs/config

**Comment by ybaldus** [comment]
I created #1228. This one misses the integration tests because we do not test the release action at moment at all and I don't really know where to start.

**Comment by MarcoIeni** [comment]
Thanks for the PR, I will have a look 🙏 
Btw, we test the `release` command [here](https://github.com/MarcoIeni/release-plz/blob/9beef23567fe4630e4a284b0310a124452fc23d8/crates/release_plz/tests/all/changelog.rs#L23)

**Comment by ybaldus** [comment]
Okay thank you, I will take a look at it.

I just found out that I broke [this](https://github.com/MarcoIeni/release-plz/blob/9beef23567fe4630e4a284b0310a124452fc23d8/crates/release_plz/src/args/release.rs#L201) test and I don't know why.

**Comment by MarcoIeni** [comment]
I fixed the test 👍
