### ISSUE TITLE
Early exit from `release` causes crates to not be released

### ISSUE THREAD

**Issue by satlank** [MarcoIeni/release-plz#686]
## Bug description

In some circumstances, `release-plz release` will not publish crates in a workspace.

## To Reproduce

The way I encountered this is a bit of an edge case, but I think this can also be triggered in other situations (see below for more detail on that): If you have a repository with a single `crate-a` (i.e. not a workspace), and do a release, you will end up with a tag `v0.1.0` (or similar) and a published `crate-a`. If you then rework the repository to be a worksapce and add a new `crate-b` that depends on `crate-a` and try to do a new release (and `crate-a` does **not** need a new release), `release-plz` will not publish `crate-b`.

## Expected behavior

It should publish everything that needs publishing.

## Environment

- OS: Linux
- release-plz version: 0.2.58, 0.2.63 (that's all I tested, looks like main will be affected as well)

## Additional context

This issue is caused by the [early return here](https://github.com/MarcoIeni/release-plz/blob/release-plz-v0.2.63/crates/release_plz_core/src/release.rs#L201), and the fact that it didn't reach the [`continue` here](https://github.com/MarcoIeni/release-plz/blob/release-plz-v0.2.63/crates/release_plz_core/src/release.rs#L195) because it is now (sensibly) checking for tag `crate-a-v0.1.0` and not the previously created `v0.1.0`.

The work-around is to just create the tag it is looking for, but I am not sure the [`return` here](https://github.com/MarcoIeni/release-plz/blob/release-plz-v0.2.63/crates/release_plz_core/src/release.rs#L201) is correct, should that not be a `continue` instead? It looks like it would also cause problems if a crate is published to multiple registries and it happens to already be present on one of them (and then would not publish to the remaining registries it hasn't checked yet).

Happy to submit a PR for the one-line change, but wanted to check first whether I am not missing something and the `return` is there for a reason.

**Comment by MarcoIeni** [comment]
Steffen, thank you for reporting this and correctly pointing to the solution 💯 
You are right, the return there is bad.
Should we replace the `return Ok(());` with a `continue;`?
If you agree, please open a PR 🙏

**Comment by satlank** [comment]
Cool, created [a PR](https://github.com/MarcoIeni/release-plz/pull/691) for this.

**Comment by MarcoIeni** [comment]
Merged, thanks!
