### ISSUE TITLE
Breaking changes stated in commit messages do not bump the major version

### ISSUE THREAD

**Issue by TobTheRock** [MarcoIeni/release-plz#687]
## Bug description

Currently a commit message containing a breaking change footer does not lead to a major version bump. This happens when either `SemVerCheck` is disabled or is unable to detect a breaking API change. There is already a [code path](https://github.com/MarcoIeni/release-plz/blob/main/crates/release_plz_core/src/version.rs#L20) with a proper version detection logic for commit messages. However only commit message headers are passed, so that the footer is never evaluated.

## To Reproduce

1. Have a commit message with a  breaking change footer, e .g.
```
feat: xyz

BREAKING CHANGE: blubb
``` 
2.  Disable `SemVerCheck` with a `release-plz.toml`:
``` 
[workspace]
semver_check = "no"
``` 
3. Run `release-plz update`

Reproducable on `main`, this only leads to a minor version bump.

## Expected behavior

Major version bump.

## Environment

- OS: Manjaro Linux 
- release-plz version: upstream main

## Additional context

If I am not mistaken, the fix can actually be quite easy. Just [change the formatting](https://github.com/MarcoIeni/release-plz/compare/main...TobTheRock:release-plz:fix/breaking-changes-not-detected) of the `git log` call, so that full raw message is returned. If desired, I can open a PR with this.

**Comment by MarcoIeni** [comment]
oh, wow, I missed that in [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) footers could contain `BREAKING CHANGE:`. Thanks for noticing this 🤯 
By looking at the [conventional_commit_parser](https://docs.rs/conventional_commit_parser/latest/conventional_commit_parser/#example-) it seems that your fix is right, so please open a PR, thanks 🙏

**Comment by MarcoIeni** [comment]
In https://github.com/MarcoIeni/release-plz/pull/690 I tested and documented this new behavior :)
Again, thanks for reporting and fixing the issue!
