### ISSUE TITLE
Action outputs

### ISSUE THREAD

**Issue by flying-sheep** [MarcoIeni/release-plz#711]
## Motivations

As mentioned in https://github.com/MarcoIeni/release-plz/discussions/709, I want to build and publish a Python package whenever release-pls creates a new tag/release.  Currently, there’s no way to figure out if it did that in a run, except for maybe parsing the logs.

- Would you like to implement this feature? y

## Solution

The GitHub action should set one or more outputs containing the information if it created a new release or a new PR.

Then subsequent steps could be run conditionally, depending on what sub-actions the release-plz action performed. 

## Alternatives

Use one of the documented ways to circumvent the workflows-can’t-trigger-workflows issue, then create a workflow that gets triggered `on: release: types: [published]`

**Comment by MarcoIeni** [comment]
I'm not sure about this. I think using the `on: release` is way cleaner than inspecting the GitHub action output. 🤔 

Also:
- in a workspace the action creates more tags at once, so you need to iterate over all tags.
- You might want to use the tag on a different architecture or operating system (for example, to build and publish the binary on macos or windows)

Also, why do you want to know if a new PR was created?

I understand that "workflows-can’t-trigger-workflows" story adds friction. In https://github.com/MarcoIeni/release-plz/pull/703 I'm trying to make the docs more straightforward.

What do you think?

**Comment by flying-sheep** [comment]
>  I think using the `on: release` is way cleaner than inspecting the GitHub action output. thinking

Yeah, I just also think it’s not super clean to have the uploads to crates.io happen in the `on: push` workflow and the uploads to PyPI happen in the `on: release` workflow.

If there was a way to turn off the crates.io upload and then do the upload separately in the `on: release` workflow, that would also work and be clean.

**Comment by MarcoIeni** [comment]
We could add a `publish` flag in the configuration file, so that release-plz doesn't upload to crates.io, so you can run `cargo publish` by yourself in the `on: release` workflow. What do you think? 🤔

**Comment by flying-sheep** [comment]
Makes sense, I’m going to comment there.
