### ISSUE TITLE
Configuration: generate json schema

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#724]
## Motivations

[Json schema](https://json-schema.org/) helps user to do less mistakes, by providing errors and autocompletions when working on the configuration file in their IDE.

## Solution

According to [even better toml](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) docs, we could upload our schema to [JSON Schema Store](https://www.schemastore.org/json/), so that IDEs understand the json schema of the `release-plz.toml` file.

Add a release-plz command to generate the json schema from serde with [schemars](https://github.com/GREsau/schemars).

Then commit the json schema to this repo and add a ci step to check if the json schema is up to date.

**Comment by AntoineGS** [comment]
Hi, I have a working prototype, it outputs this: [release-plz.json](https://github.com/MarcoIeni/release-plz/files/13493733/release-plz.json).
However I am wondering what your thought was on the CI step, is it to simply fail the CI if there is a difference in the file?
Thanks!

**Comment by MarcoIeni** [comment]
Wow, thanks!

> is it to simply fail the CI if there is a difference in the file?

Yes!

**Comment by AntoineGS** [comment]
Thanks, I just noticed [this](https://github.com/SchemaStore/schemastore/blob/8560081aaf5136d53f23fd6cf27d65dcb0a84bdf/CONTRIBUTING.md#how-to-add-a-json-schema-thats-self-hostedremoteexternal) entry on SchemaStore.
We can link to an externally hosted schema (ie on this repo), which would make keeping it up to date a lot easier.
I would keep the CI validation the same but the fix would be to simply commit the new file here instead of having to do a PR on another repo with each change.
Are you OK with hosting the schema here?

**Comment by MarcoIeni** [comment]
> Are you OK with hosting the schema here?

Yes, it seems the best solution, thanks!

**Comment by MarcoIeni** [comment]
closed the pr, now we need to add the schema to the json schema store :+1:

**Comment by MarcoIeni** [comment]
closed the pr, now we need to add the schema to the json schema store :+1:

**Comment by MarcoIeni** [comment]
closed the pr, now we need to add the schema to the json schema store :+1:

**Comment by MarcoIeni** [comment]
it works, but there are multiple entries for `git_release_type`
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/88ed5daa-4d43-4cfb-b214-2f8a5ffc2dad)

**Comment by AntoineGS** [comment]
Hmm, what IDE are you using?
I tested using RustRover (JetBrains) and I get this:
![image](https://github.com/MarcoIeni/release-plz/assets/16911399/3423d1ec-7786-4e00-82d4-5768d5aaf88c)

Though I did have to manually import the file as it did not seem to pick it up from the SchemaStore just yet.

**Comment by AntoineGS** [comment]
Nevermind, I tested on VSCode and I can see that's what you are using.
It seems to create an entry for each value of `ReleaseType` plus the actual config hence why it is four.
The descriptions also match each of the types:
![image](https://github.com/MarcoIeni/release-plz/assets/16911399/57216604-aa8e-441a-a8fc-928a689266fb)
![image](https://github.com/MarcoIeni/release-plz/assets/16911399/dc364172-c6cc-4404-a3e2-7df4fe895578)
I will see if I can find an example of another schema that has a similar structure and see how it makes it work.

**Comment by MarcoIeni** [comment]
Maybe you need an extension for the jetbrains ide?
Anyway, I'm using vscode, yes 👍

Thanks for checking 🙏

**Comment by AntoineGS** [comment]
FYI: https://github.com/tamasfe/taplo/issues/514
We should be able to change the format of the enum for it to work, but since it uses the same tags as the documentation we may need to doctor the file so as not to remove metadata used for other aspects.
PS: I am not doing much side project this week as I caught covid, I will get back to it in a couple of days! 😭

**Comment by MarcoIeni** [comment]
Have some rest! I hope you have a quick recovery ❤️

**Comment by MarcoIeni** [comment]
I checked, and the same issue happens with the cargo configuration in Cargo.toml, so I don't think it's an issue with release-plz itself. I'm marking this as completed 👍 
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/2b8e27f8-4a1e-4903-b9ba-9c78f743e5c6)

**Comment by AntoineGS** [comment]
Yeah the issue from my earlier post for taplo also seems to confirm, and that it likely not be fixed as the project is not actively maintained.
If we wanted we could work around it but we would have to parse the generated file and make convert it to a different declaration type for these :(

**Comment by MarcoIeni** [comment]
I don't think it's worth it. What we have is good enough :)
