### ISSUE TITLE
Crates.io token: detect if missing in GitHub Actions

### ISSUE THREAD

**Issue by LukeMathWalker** [MarcoIeni/release-plz#755]
## Motivations

The GitHub Action does not yell at you if you forget to set `CARGO_REGISTRY_TOKEN` as a secret in your repository.  
You instead need to pick up from the logs that the `403` returned by crates.io is indeed caused by a missing token.

- Would you like to implement this feature? N

## Solution

Proactively detect if the environment variable is missing or empty and return a clear error message.

Bonus points: call out in the `release-plz` book, in the GitHub Actions section, that setting up the registry token as a secret is a required step.

**Comment by MarcoIeni** [comment]
I updated the docs and I added the check in the github action:
![image](https://user-images.githubusercontent.com/11428655/236619040-d9433172-2894-41be-a9f1-ef0e526d77c2.png)

Thanks for taking the time to submit the suggestion! :)
