### ISSUE TITLE
Document how to use with Gitlab

### ISSUE THREAD

**Issue by radek-sprta** [MarcoIeni/release-plz#847]
## Motivations

Hello Marco,
while I understand that your main focus is Github, I did notice there is some support for Gitlab in the tool: https://github.com/MarcoIeni/release-plz/pull/591. But I feel it could be better documented to unlock the full power of the tool (as showcased here: https://gitlab.com/MarcoIeni/marco-test-gitlab/-/releases#v0.1.0).

I tried to run `release-plz` with the following options:

```
release-plz release --backend gitlab --git-token "${GITLAB_TOKEN}" --repo-url "https://gitlab.com/${USER}/${REPOSITORY}" --token "${CARGO_TOKEN}"
```

However, while the crates.io upload went fine, the tool neither created a tag, nor a Gitlab release. 

- Would you like to implement this feature? [y/n]

## Solution

Add examples to `release` sub-command documentation to showcase how to run it

**Comment by MarcoIeni** [comment]
Last time I tried, it created the tag and release.
The repository you linked is the one I used for the test.

If anybody wants to help, try to reproduce the issue, debug to find the bug and add more docs.

**Comment by MarcoIeni** [comment]
I ran `release-plz release --backend gitlab --git-token ${GITLAB_TOKEN}` and release-plz created the [tag](https://gitlab.com/MarcoIeni/marco-test-gitlab/-/tags).
However I got a 401 when creating the release:

```
  2023-08-15T17:32:21.585309Z ERROR  HTTP status client error (401 Unauthorized) for url (https://gitlab.com/api/v4/projects/MarcoIeni%2Fmarco-test-gitlab/releases)
```

So release-plz should be working.

- [ ] we need to document how to generate a gitlab token and what permissions it needs. PR welcome.

what error do you get?

**Comment by radek-sprta** [comment]
So, I wanted to look into this today, as I was about to make a new release... and both the tag and release were created fine. I did give the token all privileges this time around though. Not sure what the deal with the tag was, because I could n't get it to work last time, despite trying different combinations of parameters.

Nevertheless, I will look into the exact API token permissions needed & make a PR for the documentation.

**Comment by MarcoIeni** [comment]
That's awesome, thanks!
