### ISSUE TITLE
Filter out packages

### ISSUE THREAD

**Issue by felipellrocha** [MarcoIeni/release-plz#867]
## Motivations

I have a monorepo at work that contains multiple projects in it. I would like to maintain only a subset of these projects using release-plz. 

It there a way to filter out all other packeges from it?

- Would you like to implement this feature? [n]

## Solution

If I have a Cargo.toml:
```rs
[workspace]
members = [
  "package_a",
  "package_b",
  "package_c",
  "package_d",
  "package_e",
]
```

I should be able to configure release-plz
```rs
[workspace]
whitelist = [
  "package_b",
  "package_d",
]
```

**Comment by MarcoIeni** [comment]
release-plz ignores packages with `publish = false` in Cargo.toml.

**Comment by felipellrocha** [comment]
That worked! It would be great to have a FAQ explaining how to do common publishing things that a noob (such as myself) might be interested in learning! Great work, by the way! :)

**Comment by MarcoIeni** [comment]
Sure! Can you write down the questions to include in this FAQ? :)

**Comment by MarcoIeni** [comment]
There were some FAQ among the docs. I put them together in https://github.com/MarcoIeni/release-plz/pull/868

Feel free to open other issues or contribute if you have other doubts, or if you have good ideas for other FAQs :)

**Comment by felipellrocha** [comment]
Ah, I had missed the FAQ! :) That would have indeed solved my problem.

**Comment by MarcoIeni** [comment]
Hopefully now FAQs are more visible 👍
