### ISSUE TITLE
Update Workspace Dependents Version Number

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#877]
Currently if you use `release-plz` in a workspace which contains two crates, where crate A depends on crate B. When changes are made to crate B, `release-plz` will update B's version number in B's Cargo.toml, but will not update B's version number in A's `[dependencies]` section in A's Cargo.toml, which means that your crates will now be out of sync in terms of which version they depend on, and can lead to version resolution failures when pulling from crates.io.

**Comment by MarcoIeni** [comment]
Hi! In my experience this is not the case. Example [here](https://github.com/MarcoIeni/rust-workspace-example/pull/164/files).
Can you write an example or point me to a repository and commit so I can reproduce the issue?

**Comment by XAMPPRocky** [comment]
> Can you write an example or point me to a repository and commit so I can reproduce the issue?
https://github.com/XAMPPRocky/rasn/pull/128/

Maybe it's because I use the workspace version number for all crates, and don't have individual version numbers for each crate.

**Comment by MarcoIeni** [comment]
Thank you for opening the issue! 🙏 
I'm releasing the new version of release-plz right now. 1 hour or so and your github action should work correctly 👍

**Comment by MarcoIeni** [comment]
New GitHub action version released ✅
