### ISSUE TITLE
Tests fail without docker installed

### ISSUE THREAD

**Issue by orhun** [MarcoIeni/release-plz#911]
## Bug description

Hey, I got these test failures during the Arch Linux build of `0.3.18`:

```
running 3 tests
test helpers::gitea::gitea_new::can_create_gitea_repository ... FAILED
test changelog::release_plz_adds_changelog_on_new_project ... FAILED
test completion_test::test_generate_completions ... ok

failures:

---- helpers::gitea::gitea_new::can_create_gitea_repository stdout ----
thread 'helpers::gitea::gitea_new::can_create_gitea_repository' panicked at 'Failed to create user: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/release_plz/tests/all/helpers/gitea/gitea_new.rs:91:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- changelog::release_plz_adds_changelog_on_new_project stdout ----
thread 'changelog::release_plz_adds_changelog_on_new_project' panicked at 'Failed to create user: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/release_plz/tests/all/helpers/gitea/gitea_new.rs:91:10


failures:
    changelog::release_plz_adds_changelog_on_new_project
    helpers::gitea::gitea_new::can_create_gitea_repository

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.16s

error: test failed, to rerun pass `-p release-plz --test all`
```

I think it is due to the use of `docker` in tests:

https://github.com/MarcoIeni/release-plz/blob/2f11269279801be6c6ff9aa589b93f3fb6c97b51/crates/release_plz/tests/all/helpers/gitea/gitea_new.rs#L74-L78

I would prefer not to use `docker` as a `checkdepends` since it is a heavy dependency. I don't know if we can figure out another way though.

- Would you like to work on a fix? [y/n]

y

## To Reproduce

1. Fetch the latest [`PKGBUILD`](https://gitlab.archlinux.org/archlinux/packaging/packages/release-plz/-/blob/main/PKGBUILD)
2. Build in a clean chroot (`extra-x86_64-build`)

## Expected behavior

Successful build with tests passing.

## Screenshots

\-

## Environment

- OS: Arch Linux
- release-plz version: `0.3.18`

## Additional context

I updated the package with these tests skipped. Let me know if we can figure out a workaround.

**Comment by MarcoIeni** [comment]
Hey Orhun 👋 

Yes, I added docker to the test suite, so that I can test that release-plz opens a PR on a real Gitea instance! 😎

Two solutions comes to my mind:
- To build the arch package, you only run `cargo check`, without running `cargo test`. Is this acceptable?
- I add a feature flag that disables tests that depend on docker. You can run the tests with/without this flag. This makes maintenance more difficult because contributors need to remember this flag when editing tests.

**Comment by orhun** [comment]
> I add a feature flag that disables tests that depend on docker. You can run the tests with/without this flag. This makes maintenance more difficult because contributors need to remember this flag when editing tests.

I think this is the most viable option. You can enable this feature as default so that docker tests run as default 🐻
