### ISSUE TITLE
Pass commit IDs to git-cliff

### ISSUE THREAD

**Issue by aschey** [MarcoIeni/release-plz#954]
Hi, thanks for creating this project! It's really easy to use and the results have been great.

## Motivations 
When the changelog is created, the actual commit IDs don't get passed along to `git-cliff`, it uses a dummy value instead: https://github.com/MarcoIeni/release-plz/blob/a88c026880d98da1a4884f7e73a937304a90d1f3/crates/release_plz_core/src/changelog.rs#L131

If your `git-cliff` config references the commit ID in the template like in [their example](https://github.com/orhun/git-cliff/blob/890de0007e108059378b134e9b9d0af2a6965027/cliff.toml#L27-L30):
```
{% macro commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }} - ([{{ commit.id | truncate(length=7, end="") }}](<REPO>/commit/{{ commit.id }}))\
{% endmacro -%}
``` 

it will just show the dummy value instead of the actual commit ID.

- Would you like to implement this feature? 
I'd be happy to submit a PR.

## Solution

The commit ID is already retrieved here: https://github.com/MarcoIeni/release-plz/blob/a88c026880d98da1a4884f7e73a937304a90d1f3/crates/release_plz_core/src/next_ver.rs#L709

I think we just need to pass that info along with the commit message when the changelog is created.

## Alternatives

None that I can think of.

**Comment by MarcoIeni** [comment]
Thank you! Feel free to open a PR 👍
