### ISSUE TITLE
Improve documentation and error handling for existing changelog

### ISSUE THREAD

**Issue by robo9k** [MarcoIeni/release-plz#970]
## Motivations

I have a project where I've had to manually create a `CHANGELOG.md` since the old commits weren't conventional and also not exactly usable for change descriptions as-is.
From what I've gathered, this use-case isn't documented anywhere for `release-plz`. It might also be more an issue for `git-cliff`, but read on.

An initial attempt using `release-plz-action` added a duplicate changelog header, i.e. the thing between and including `# CHANGELOG` and `## Unreleased` was already present in my file and another one was added by `release-pr`.

Furthermore I messed up my manually created `CHANGELOG.md` by including some versions multiple times. The `release-plz-action` only logs the following:
```
WARN  can't determine changes in changelog of package example: can't parse changelog
```
Whereas there is more info:
```rust
        let content = include_str!("CHANGELOG.md");
        let changelog = parse_changelog::parse(content).unwrap();
        println!("{:?}", changelog);
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Parse("multiple release notes for '4.2.0'"))', src/main.rs:3:53
```
I don't really know how to debug the action here, since does things (like populating the "Changes" details in the pull request description) that a simple `release-plz update` doesn't do locally and I don't want to create a bunch of throwaway debug pull requests in my actual repo.

- Would you like to implement this feature? [n]

## Solution

- [ ] I'd like the `release-plz` documentation to describe in more detail how it handles existing `CHANGELOG.md` files when updating them, e.g. what can be present, what must be present and which formats are possible.
- [x] I'd like the `releaes-plz-action` to have more detailed log messages when something goes wrong, here parsing the changes in the changelog.

## Alternatives

I guess if you create your whole changelog with `release-plz` you won't run into those problems, so it might be a low priority issue not worth fixing.

## Additional context

`MarcoIeni/release-plz-action@63d791e17e2f2369d173fb6b81b401029e16e04f # v0.5.20`
```terminal
$ release-plz --version
release-plz 0.3.23
```

**Comment by MarcoIeni** [comment]
This is super valuable feedback. Thank you!

> The release-plz-action only logs the following

Whoops. I was only printing the `Display` representation of the error. Not the `Debug` one. Sometimes I wish the `Display` implementation of anyhow also shows the context of the error. It would be handy if there was a way to lint when you print the `Display` of an error instead of the `Debug`.

Fixed in https://github.com/MarcoIeni/release-plz/pull/971

I agree that the changelog part is not documented properly, but it's a huge effort and I have some changes in mind (e.g. in the future I want to hide git-cliff from the users, so that they are exposed to less stuff). How can I help you in the meantime? Please share the changelog where you are having troubles.

**Comment by robo9k** [comment]
I've tried to quickly reproduce the issue of duplicate header text in the `CHANGELOG.md` in a merge request but abandoned that due to the bunch of external factors (previous commits, existing tags, existing published crate versions).

I'm not sure if it's helpful now, but in the actual repo in questions:

1. https://github.com/robo9k/rust-magic/pull/72/files is where I added my manual `CHANGELOG.md` initially
note that the format with the header etc. was taken from the `release-plz` diff 
3. https://github.com/robo9k/rust-magic/pull/73/files is where I noticed the duplicated header (then added by `release-plz` in its open merge request) and tried to workaround that by just removing it from my manual file
4. https://github.com/robo9k/rust-magic/pull/74/files is where I removed a duplicate version from my manual `CHANGELOG.md`
5. https://github.com/robo9k/rust-magic/pull/75/files is where I removed another duplicate version from my manual `CHANGELOG.md`
6. https://github.com/robo9k/rust-magic/pull/70 is a `release-plz` release that looks okay now, with a non-empty expandable Changelog in the description and the new version (and its own hardcoded header) added to the `CHANGELOG.md`

**Comment by MarcoIeni** [comment]
Ok, so it seems that everything is good now. Glad to hear that. Thank you for opening this issue and for the detailed explanation. 👍

**Comment by robo9k** [comment]
I've now successfully had `release-plz` publish its first release and its next pull request also has a proper changelog, so it might have been unlucky circumstances 🤷‍♂️

**Comment by MarcoIeni** [comment]
Since we solved your particular issue, I'm closing this one and opening https://github.com/MarcoIeni/release-plz/issues/1006 to track your request about having better changelog docs. Thanks. 👍
