### ISSUE TITLE
Possible changes for "Use a GitHub Action"

### ISSUE THREAD

**Issue by robo9k** [MarcoIeni/release-plz#999]
## Motivations

I did not want the `release-plz` pull requests to have me as the author due to use of a PAT, so I followed https://release-plz.ieni.dev/docs/github/trigger#use-a-github-action and am suggesting some changes below.

- One can create a private GitHub App instead of a public one,
this removes the need to explain it can't be really installed for anyone else as in https://github.com/apps/release-plz
- One can use the official [`actions/create-github-app-token` ](https://github.com/actions/create-github-app-token) action instead of `tibdex/github-app-token` (at least from my limited testing: successfully created pull request)
- the previously mentioned action's documentation does not seem to consider the App id to be a secret and uses a regular variable instead
- the `release-plz` commit info seems to be hardcoded to
```
Author: release-plz <release-plz@github.com>
```
- the `release-plz` sign-off (see #955) seems to be hardcoded to
```
Signed-off-by: release-plz <release-plz@github.com>
```

You can take a look my configuration as an example in:
- https://github.com/robo9k/rust-magic/blob/main/.github/workflows/release.yml
- https://github.com/robo9k/rust-magic/pull/104
- https://github.com/robo9k/rust-magic/pull/104/commits/9b26db52c6b08772a6edd9b6e6ea0b1964ac1b92
- https://github.com/apps/arbeitsmaschine

Would you like to implement this feature? [y/n] maybe?

## Solution

- [x] Update the documentation on how to use a GitHub App (not "GitHub Action" as the heading currently says) according to the description here,
see #1013
- [x] Make the commit Author and sign-off configurable
see https://github.com/MarcoIeni/release-plz-action/pull/85

## Alternatives

Keep everything as-is :)

## Additional context

The proposed changes would make it less visible that `release-plz` is used, the only place where it'd remain mentioned as far as I see is in the pull request ("This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/)"),
so I'd understand if you'd rather keep everything as-is.

Once `Author` is configurable, I think I have the syntax to make GitHub actually link commits to the GitHub app (instead of the unlickable "release-plz" text), see https://github.com/robo9k/rust-magic/commit/6d280e3566fbf34b98f83021edb8dc30043e831b (which shows separate "robo9k commited" since it I pushed the commit with my identity), compare from https://github.com/MarcoIeni/release-plz/pull/997/commits/f8bae258f2cae2c623ea73468ae1a4d0096fff77

**Comment by MarcoIeni** [comment]
Thank you for all the awesome feedback and suggestion you are giving! I will review this and the PR you opened asap :)

**Comment by robo9k** [comment]
Might also be worth noting that when using a GitHub App with protected tags, it needs "Repository administration: write", which is a bit unfortunate
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules

**Comment by MarcoIeni** [comment]
Feel free to improve release-plz docs. All the suggestions seem reasonable!
Regarding making the author configurable, sure, no problem: what I do in release-plz is just adding `-s` to the commit [here](https://github.com/MarcoIeni/release-plz/blob/20101a9d574f41f0583ad723ee74114af277432e/crates/git_cmd/src/lib.rs#L128).

I think the issue is that in the github action I set the author [here](https://github.com/MarcoIeni/release-plz-action/blob/ce393af6a01a1c994bf8a0f469c015dc5593dfbe/action.yml#L59). How can we detect the author from the token, similarly to how renovate does? It should also work if a git token is unspecified.

**Comment by robo9k** [comment]
@MarcoIeni I've added pull requests for both tasks and linked them in the updated issue description

**Comment by MarcoIeni** [comment]
Thanks for you help! ❤️
